In [1]:
# ============================================================
# STEP 1 — FIND THE ORIGINAL DATASET
# ============================================================

import os

for dirname, _, filenames in os.walk("/kaggle/input"):
    for filename in filenames:
        print(
            os.path.join(dirname, filename)
        )

/kaggle/input/datasets/prasad22/daily-transactions-dataset/Daily Household Transactions.csv

In [2]:
# ============================================================
# STEP 2 — LOAD ORIGINAL DATASET
# ============================================================

import pandas as pd

DATA_PATH = "/kaggle/input/datasets/prasad22/daily-transactions-dataset/Daily Household Transactions.csv"

df = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully!")

print("\nDataset shape:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 10 rows:")
display(df.head(10))

Dataset loaded successfully!

Dataset shape:
(2461, 8)

Columns:
['Date', 'Mode', 'Category', 'Subcategory', 'Note', 'Amount', 'Income/Expense', 'Currency']

First 10 rows:

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
0,20/09/2018 12:04:08,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,INR
1,20/09/2018 12:03:15,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,INR
2,19/09/2018,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,INR
3,17/09/2018 23:41:17,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,INR
4,16/09/2018 17:15:08,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,INR
5,15/09/2018 06:34:17,Credit Card,subscription,Tata Sky,Permanent Residence - Tata Play recharge,200.0,Expense,INR
6,14/09/2018 05:39:17,Cash,Transportation,auto,Place 2 station to Permanent Residence,50.0,Expense,INR
7,13/09/2018 21:35:15,Saving Bank account 1,Transportation,Train,2 Place 0 to Place 3,40.0,Expense,INR
8,13/09/2018 21:01:47,Credit Card,Other,NaN,HBR 2 Months subscription,83.0,Expense,INR
9,13/09/2018 21:01:32,Cash,Food,Grocery,1kg atta,46.0,Expense,INR

In [3]:
# ============================================================
# STEP 3 — KEEP REQUIRED COLUMNS
# ============================================================

# Keep only the columns needed for our classification task
df = df[
    [
        "Note",
        "Category",
        "Income/Expense"
    ]
].dropna()

# Rename them to simpler names
df.columns = [
    "text",
    "category",
    "type"
]

print("Shape after cleaning:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nTransaction types:")
print(df["type"].unique())

print("\nOriginal categories:")
print(df["category"].unique())

print("\nFirst 10 cleaned rows:")
display(df.head(10))

Shape after cleaning:
(1940, 3)

Columns:
['text', 'category', 'type']

Transaction types:
['Expense' 'Income' 'Transfer-Out']

Original categories:
['Transportation' 'Food' 'subscription' 'Festivals' 'Other' 'Apparel'
 'Gift' 'Salary' 'Household' 'Dividend earned on Shares' 'Interest'
 'Beauty' 'Health' 'Family' 'maid' 'Culture' 'Tourism'
 'Saving Bank account 1' 'Self-development' 'Education' 'Petty cash'
 'Documents' 'Social Life' 'Maturity amount' 'Equity Mutual Fund D'
 'Share Market' 'Gpay Reward' 'Equity Mutual Fund E'
 'Equity Mutual Fund A' 'Equity Mutual Fund F' 'Recurring Deposit'
 'Fixed Deposit' 'Money transfer' 'Bonus' 'Investment' 'Grooming'
 'Public Provident Fund' 'water (jar /tanker)']

First 10 cleaned rows:

                                       text        category     type
0                      2 Place 5 to Place 0  Transportation  Expense
1               Idli medu Vada mix 2 plates            Food  Expense
2                      1 month subscription    subscription  Expense
3                         Data booster pack    subscription  Expense
4                               Ganesh idol       Festivals  Expense
5  Permanent Residence - Tata Play recharge    subscription  Expense
6    Place 2 station to Permanent Residence  Transportation  Expense
7                      2 Place 0 to Place 3  Transportation  Expense
8                 HBR 2 Months subscription           Other  Expense
9                                  1kg atta            Food  Expense

In [4]:
# ============================================================
# STEP 4 — CHECK CATEGORY AND TYPE DISTRIBUTION
# ============================================================

print("============================================================")
print("CATEGORY DISTRIBUTION")
print("============================================================")

category_counts = df["category"].value_counts()

print(category_counts)


print("\n============================================================")
print("TYPE DISTRIBUTION")
print("============================================================")

type_counts = df["type"].value_counts()

print(type_counts)


print("\n============================================================")
print("NUMBER OF UNIQUE RAW CATEGORIES")
print("============================================================")

print(
    "Unique categories:",
    df["category"].nunique()
)


print("\n============================================================")
print("NUMBER OF UNIQUE TYPES")
print("============================================================")

print(
    "Unique types:",
    df["type"].nunique()
)


print("\n============================================================")
print("RARE CATEGORIES")
print("============================================================")

print(
    category_counts[
        category_counts <= 20
    ]
)


print("\n============================================================")
print("MOST COMMON CATEGORIES")
print("============================================================")

print(
    category_counts.head(10)
)

============================================================
CATEGORY DISTRIBUTION
============================================================
category
Food                         831
Transportation               302
Household                    164
Other                        125
subscription                  92
Health                        87
Investment                    55
Apparel                       47
Salary                        43
Gift                          30
Family                        23
Beauty                        21
Education                     18
Festivals                     16
Interest                      12
Dividend earned on Shares     12
Culture                       11
Petty cash                     6
Maturity amount                6
Bonus                          6
Tourism                        5
Saving Bank account 1          4
Grooming                       4
Documents                      2
maid                           2
Self-development               2
water (jar /tanker)            2
Gpay Reward                    2
Equity Mutual Fund D           1
Social Life                    1
Equity Mutual Fund F           1
Equity Mutual Fund A           1
Equity Mutual Fund E           1
Share Market                   1
Money transfer                 1
Fixed Deposit                  1
Recurring Deposit              1
Public Provident Fund          1
Name: count, dtype: int64

============================================================
TYPE DISTRIBUTION
============================================================
type
Expense         1830
Income            99
Transfer-Out      11
Name: count, dtype: int64

============================================================
NUMBER OF UNIQUE RAW CATEGORIES
============================================================
Unique categories: 38

============================================================
NUMBER OF UNIQUE TYPES
============================================================
Unique types: 3

============================================================
RARE CATEGORIES
============================================================
category
Education                    18
Festivals                    16
Interest                     12
Dividend earned on Shares    12
Culture                      11
Petty cash                    6
Maturity amount               6
Bonus                         6
Tourism                       5
Saving Bank account 1         4
Grooming                      4
Documents                     2
maid                          2
Self-development              2
water (jar /tanker)           2
Gpay Reward                   2
Equity Mutual Fund D          1
Social Life                   1
Equity Mutual Fund F          1
Equity Mutual Fund A          1
Equity Mutual Fund E          1
Share Market                  1
Money transfer                1
Fixed Deposit                 1
Recurring Deposit             1
Public Provident Fund         1
Name: count, dtype: int64

============================================================
MOST COMMON CATEGORIES
============================================================
category
Food              831
Transportation    302
Household         164
Other             125
subscription       92
Health             87
Investment         55
Apparel            47
Salary             43
Gift               30
Name: count, dtype: int64

In [5]:
# ============================================================
# STEP 5 — REMOVE TRANSFER-OUT
# ============================================================

print("Before removing Transfer-Out:")
print("Rows:", len(df))

print("\nTransaction types:")
print(df["type"].value_counts())


# Remove Transfer-Out transactions
df = df[
    df["type"] != "Transfer-Out"
].reset_index(drop=True)


print("\n============================================================")
print("AFTER REMOVING TRANSFER-OUT")
print("============================================================")

print("Remaining rows:", len(df))

print("\nTransaction types:")
print(df["type"].value_counts())

Before removing Transfer-Out:
Rows: 1940

Transaction types:
type
Expense         1830
Income            99
Transfer-Out      11
Name: count, dtype: int64

============================================================
AFTER REMOVING TRANSFER-OUT
============================================================
Remaining rows: 1929

Transaction types:
type
Expense    1830
Income       99
Name: count, dtype: int64

In [6]:
# ============================================================
# STEP 6 — MAP RAW CATEGORIES TO FINAL 15 CATEGORIES
# ============================================================

category_mapping = {

    # --------------------------------------------------------
    # FOOD
    # --------------------------------------------------------
    "Food": "Food",

    # --------------------------------------------------------
    # TRANSPORTATION
    # --------------------------------------------------------
    "Transportation": "Transportation",

    # --------------------------------------------------------
    # HOUSEHOLD
    # --------------------------------------------------------
    "Household": "Household",
    "water (jar /tanker)": "Household",
    "maid": "Household",
    "Cook": "Household",
    "Rent": "Household",
    "garbage disposal": "Household",

    # --------------------------------------------------------
    # OTHER
    # --------------------------------------------------------
    "Other": "Other",
    "Petty cash": "Other",
    "Documents": "Other",
    "Money transfer": "Other",
    "Gpay Reward": "Other",
    "Social Life": "Other",
    "scrap": "Other",

    # --------------------------------------------------------
    # SUBSCRIPTION
    # --------------------------------------------------------
    "subscription": "Subscription",

    # --------------------------------------------------------
    # HEALTH
    # --------------------------------------------------------
    "Health": "Health",

    # --------------------------------------------------------
    # INVESTMENT
    # --------------------------------------------------------
    "Investment": "Investment",
    "Interest": "Investment",
    "Dividend earned on Shares": "Investment",
    "Maturity amount": "Investment",
    "Bonus": "Investment",
    "Saving Bank account 1": "Investment",
    "Saving Bank account 2": "Investment",
    "Equity Mutual Fund A": "Investment",
    "Equity Mutual Fund B": "Investment",
    "Equity Mutual Fund C": "Investment",
    "Equity Mutual Fund D": "Investment",
    "Equity Mutual Fund E": "Investment",
    "Equity Mutual Fund F": "Investment",
    "Share Market": "Investment",
    "Fixed Deposit": "Investment",
    "Recurring Deposit": "Investment",
    "Public Provident Fund": "Investment",
    "Life Insurance": "Investment",
    "Small Cap fund 1": "Investment",
    "Small Cap fund 2": "Investment",
    "Small cap fund 1": "Investment",
    "Small cap fund 2": "Investment",
    "Tax refund": "Investment",

    # --------------------------------------------------------
    # APPAREL
    # --------------------------------------------------------
    "Apparel": "Apparel",

    # --------------------------------------------------------
    # SALARY
    # --------------------------------------------------------
    "Salary": "Salary",

    # --------------------------------------------------------
    # GIFT
    # --------------------------------------------------------
    "Gift": "Gift",

    # --------------------------------------------------------
    # FAMILY
    # --------------------------------------------------------
    "Family": "Family",

    # --------------------------------------------------------
    # BEAUTY
    # --------------------------------------------------------
    "Beauty": "Beauty",
    "Grooming": "Beauty",

    # --------------------------------------------------------
    # EDUCATION
    # --------------------------------------------------------
    "Education": "Education",
    "Self-development": "Education",

    # --------------------------------------------------------
    # FESTIVALS
    # --------------------------------------------------------
    "Festivals": "Festivals",

    # --------------------------------------------------------
    # LEISURE
    # --------------------------------------------------------
    "Culture": "Leisure",
    "Tourism": "Leisure",
}


# ============================================================
# APPLY THE MAPPING
# ============================================================

df["category"] = df["category"].map(
    category_mapping
)


# ============================================================
# CHECK WHETHER ANY CATEGORY FAILED TO MAP
# ============================================================

missing_categories = df["category"].isna().sum()

print(
    "Missing categories after mapping:",
    missing_categories
)


# ============================================================
# SHOW FINAL CATEGORY LIST
# ============================================================

print("\nFinal categories:")

final_categories = sorted(
    df["category"].dropna().unique()
)

for i, category in enumerate(
    final_categories,
    start=1
):
    print(
        f"{i}. {category}"
    )


# ============================================================
# NUMBER OF FINAL CATEGORIES
# ============================================================

print(
    "\nNumber of final categories:",
    df["category"].nunique()
)


# ============================================================
# FINAL CATEGORY DISTRIBUTION
# ============================================================

print(
    "\nFinal category distribution:"
)

print(
    df["category"].value_counts()
)

Missing categories after mapping: 0

Final categories:
1. Apparel
2. Beauty
3. Education
4. Family
5. Festivals
6. Food
7. Gift
8. Health
9. Household
10. Investment
11. Leisure
12. Other
13. Salary
14. Subscription
15. Transportation

Number of final categories: 15

Final category distribution:
category
Food              831
Transportation    302
Household         168
Other             137
Subscription       92
Investment         92
Health             87
Apparel            47
Salary             43
Gift               30
Beauty             25
Family             23
Education          20
Festivals          16
Leisure            16
Name: count, dtype: int64

In [7]:
# ============================================================
# STEP 7 — REMOVE UNMAPPED ROWS AND VERIFY FINAL DATASET
# ============================================================

# Remove rows where category mapping failed
df = df.dropna(
    subset=["category"]
).reset_index(drop=True)

print("Final dataset size:", len(df))

print("\nNumber of categories:")
print(df["category"].nunique())

print("\nFinal categories:")
print(
    sorted(
        df["category"].unique()
    )
)

print("\nFinal category distribution:")
print(
    df["category"].value_counts()
)

print("\nFinal transaction type distribution:")
print(
    df["type"].value_counts()
)

Final dataset size: 1929

Number of categories:
15

Final categories:
['Apparel', 'Beauty', 'Education', 'Family', 'Festivals', 'Food', 'Gift', 'Health', 'Household', 'Investment', 'Leisure', 'Other', 'Salary', 'Subscription', 'Transportation']

Final category distribution:
category
Food              831
Transportation    302
Household         168
Other             137
Subscription       92
Investment         92
Health             87
Apparel            47
Salary             43
Gift               30
Beauty             25
Family             23
Education          20
Festivals          16
Leisure            16
Name: count, dtype: int64

Final transaction type distribution:
type
Expense    1830
Income       99
Name: count, dtype: int64

In [8]:
# ============================================================
# STEP 8 — CREATE NUMERICAL LABEL IDS
# ============================================================

# ------------------------------------------------------------
# 1. Create sorted label lists
# ------------------------------------------------------------

type_labels = sorted(
    df["type"].unique()
)

category_labels = sorted(
    df["category"].unique()
)


# ------------------------------------------------------------
# 2. Create text → number mappings
# ------------------------------------------------------------

type_to_id = {
    label: i
    for i, label in enumerate(type_labels)
}

category_to_id = {
    label: i
    for i, label in enumerate(category_labels)
}


# ------------------------------------------------------------
# 3. Add numerical IDs to dataframe
# ------------------------------------------------------------

df["type_id"] = df["type"].map(
    type_to_id
)

df["category_id"] = df["category"].map(
    category_to_id
)


# ------------------------------------------------------------
# 4. Display type labels
# ------------------------------------------------------------

print("TYPE LABELS")
print("=" * 50)

for label, idx in type_to_id.items():
    print(
        f"{idx} = {label}"
    )


# ------------------------------------------------------------
# 5. Display category labels
# ------------------------------------------------------------

print("\nCATEGORY LABELS")
print("=" * 50)

for label, idx in category_to_id.items():
    print(
        f"{idx} = {label}"
    )


# ------------------------------------------------------------
# 6. Check number of labels
# ------------------------------------------------------------

print("\nNumber of types:")
print(len(type_labels))

print("\nNumber of categories:")
print(len(category_labels))


# ------------------------------------------------------------
# 7. Verify that IDs were created correctly
# ------------------------------------------------------------

print("\nMissing type IDs:")
print(
    df["type_id"].isna().sum()
)

print("\nMissing category IDs:")
print(
    df["category_id"].isna().sum()
)


# ------------------------------------------------------------
# 8. Show sample
# ------------------------------------------------------------

print("\nSAMPLE WITH NUMERICAL LABELS")

display(
    df[
        [
            "text",
            "type",
            "type_id",
            "category",
            "category_id"
        ]
    ].head(10)
)

TYPE LABELS
==================================================
0 = Expense
1 = Income

CATEGORY LABELS
==================================================
0 = Apparel
1 = Beauty
2 = Education
3 = Family
4 = Festivals
5 = Food
6 = Gift
7 = Health
8 = Household
9 = Investment
10 = Leisure
11 = Other
12 = Salary
13 = Subscription
14 = Transportation

Number of types:
2

Number of categories:
15

Missing type IDs:
0

Missing category IDs:
0

SAMPLE WITH NUMERICAL LABELS

,text,type,type_id,category,category_id
0,2 Place 5 to Place 0,Expense,0,Transportation,14
1,Idli medu Vada mix 2 plates,Expense,0,Food,5
2,1 month subscription,Expense,0,Subscription,13
3,Data booster pack,Expense,0,Subscription,13
4,Ganesh idol,Expense,0,Festivals,4
5,Permanent Residence - Tata Play recharge,Expense,0,Subscription,13
6,Place 2 station to Permanent Residence,Expense,0,Transportation,14
7,2 Place 0 to Place 3,Expense,0,Transportation,14
8,HBR 2 Months subscription,Expense,0,Other,11
9,1kg atta,Expense,0,Food,5

In [9]:
# ============================================================
# STEP 9 — CHECK DUPLICATE / REPEATED TRANSACTION TEXT
# ============================================================

# ------------------------------------------------------------
# 1. Total rows
# ------------------------------------------------------------

print("=" * 60)
print("DATASET SIZE")
print("=" * 60)

print("Total rows:", len(df))


# ------------------------------------------------------------
# 2. Number of unique texts
# ------------------------------------------------------------

unique_texts = df["text"].nunique()

print("\nUnique transaction texts:")
print(unique_texts)


# ------------------------------------------------------------
# 3. Number of duplicated rows based on text
# ------------------------------------------------------------

duplicate_text_rows = (
    df["text"].duplicated(keep=False).sum()
)

print("\nRows belonging to repeated-text groups:")
print(duplicate_text_rows)


# ------------------------------------------------------------
# 4. Number of repeated text groups
# ------------------------------------------------------------

text_counts = (
    df["text"]
    .value_counts()
)

repeated_groups = (
    text_counts[text_counts > 1]
)

print("\nNumber of repeated text groups:")
print(len(repeated_groups))


# ------------------------------------------------------------
# 5. Show the most repeated texts
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("MOST REPEATED TRANSACTION TEXTS")
print("=" * 60)

print(
    repeated_groups.head(20)
)


# ------------------------------------------------------------
# 6. Check whether repeated texts have conflicting labels
# ------------------------------------------------------------

text_category_counts = (
    df.groupby("text")["category"]
    .nunique()
)

conflicting_texts = (
    text_category_counts[
        text_category_counts > 1
    ]
)

print("\n" + "=" * 60)
print("CONFLICTING TEXT LABELS")
print("=" * 60)

print(
    "Texts associated with multiple categories:",
    len(conflicting_texts)
)


# ------------------------------------------------------------
# 7. Display conflicting examples
# ------------------------------------------------------------

if len(conflicting_texts) > 0:

    print("\nExamples of conflicting texts:")

    conflicting_examples = df[
        df["text"].isin(
            conflicting_texts.index
        )
    ]

    display(
        conflicting_examples[
            [
                "text",
                "category",
                "type"
            ]
        ].sort_values("text").head(30)
    )


# ------------------------------------------------------------
# 8. Duplicate percentage
# ------------------------------------------------------------

duplicate_percentage = (
    duplicate_text_rows
    / len(df)
    * 100
)

print(
    f"\nPercentage of rows in repeated-text groups: "
    f"{duplicate_percentage:.2f}%"
)

============================================================
DATASET SIZE
============================================================
Total rows: 1929

Unique transaction texts:
1050

Rows belonging to repeated-text groups:
1106

Number of repeated text groups:
227

============================================================
MOST REPEATED TRANSACTION TEXTS
============================================================
text
milk 1lit                                   67
From workplace                              43
Half lit  milk                              31
1 lit                                       26
Supermart                                   25
Catering Service                            22
Mobile Service Provider recharge wfh        19
2 Current Residence to Place 0              19
tea                                         18
2 Place 0 to Current Residence              16
6 eggs                                      16
milk half shakti                            15
within city                                 15
Data booster pack                           14
Current Residence to Place 0                13
chocobar                                    13
interest paid                               12
Permanent Residence - Tata Play recharge    11
flour mill                                  11
From Family                                 11
Name: count, dtype: int64

============================================================
CONFLICTING TEXT LABELS
============================================================
Texts associated with multiple categories: 15

Examples of conflicting texts:

                                           text      category     type
16                                  Amul butter          Food  Expense
497                                 Amul butter     Household  Expense
612                                 Amul butter          Food  Expense
900                                 Amul butter          Food  Expense
1071                                    Courier     Education  Expense
984                                     Courier         Other  Expense
865     Family Mobile Service Provider recharge  Subscription  Expense
1518    Family Mobile Service Provider recharge        Family  Expense
202                                    Marathon     Education  Expense
506                                    Marathon         Other  Expense
658                                    Marathon     Education  Expense
1693  Mobile Service Provider recharge 365 days         Other  Expense
1513  Mobile Service Provider recharge 365 days  Subscription  Expense
1414       Mobile Service Provider recharge wfh  Subscription  Expense
1565       Mobile Service Provider recharge wfh  Subscription  Expense
1571       Mobile Service Provider recharge wfh  Subscription  Expense
1577       Mobile Service Provider recharge wfh  Subscription  Expense
1590       Mobile Service Provider recharge wfh  Subscription  Expense
1599       Mobile Service Provider recharge wfh  Subscription  Expense
1407       Mobile Service Provider recharge wfh  Subscription  Expense
1660       Mobile Service Provider recharge wfh         Other  Expense
1388       Mobile Service Provider recharge wfh  Subscription  Expense
1632       Mobile Service Provider recharge wfh         Other  Expense
1368       Mobile Service Provider recharge wfh  Subscription  Expense
1331       Mobile Service Provider recharge wfh  Subscription  Expense
1380       Mobile Service Provider recharge wfh  Subscription  Expense
1639       Mobile Service Provider recharge wfh         Other  Expense
1291       Mobile Service Provider recharge wfh  Subscription  Expense
1290       Mobile Service Provider recharge wfh  Subscription  Expense
1307       Mobile Service Provider recharge wfh  Subscription  Expense

Percentage of rows in repeated-text groups: 57.34%

In [10]:
# ============================================================
# STEP 10 — REMOVE AMBIGUOUS TEXTS + LEAKAGE-SAFE SPLIT
# ============================================================

from sklearn.model_selection import train_test_split


# ============================================================
# PART A — FIND TEXTS WITH CONFLICTING CATEGORIES
# ============================================================

text_category_counts = (
    df.groupby("text")["category"]
    .nunique()
)

conflicting_texts = (
    text_category_counts[
        text_category_counts > 1
    ]
    .index
)

print("=" * 65)
print("CONFLICTING TEXTS")
print("=" * 65)

print(
    "Number of conflicting text groups:",
    len(conflicting_texts)
)


# ============================================================
# PART B — SHOW THEM
# ============================================================

if len(conflicting_texts) > 0:

    print("\nConflicting texts:")

    print(
        sorted(conflicting_texts.tolist())
    )


# ============================================================
# PART C — REMOVE AMBIGUOUS TEXT GROUPS
# ============================================================

before_rows = len(df)

df_clean = df[
    ~df["text"].isin(conflicting_texts)
].copy()

df_clean = df_clean.reset_index(drop=True)

after_rows = len(df_clean)

print("\n" + "=" * 65)
print("AFTER REMOVING AMBIGUOUS TEXTS")
print("=" * 65)

print("Rows before:", before_rows)
print("Rows after:", after_rows)
print("Rows removed:", before_rows - after_rows)


# ============================================================
# PART D — VERIFY NO CONFLICTS REMAIN
# ============================================================

remaining_conflicts = (
    df_clean.groupby("text")["category"]
    .nunique()
)

remaining_conflicts = remaining_conflicts[
    remaining_conflicts > 1
]

print(
    "\nRemaining conflicting text groups:",
    len(remaining_conflicts)
)


# ============================================================
# PART E — CREATE ONE ROW PER UNIQUE TEXT
# ============================================================

# Every remaining text now has exactly one category.

group_df = (
    df_clean[
        [
            "text",
            "category"
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("\n" + "=" * 65)
print("UNIQUE TEXT GROUPS")
print("=" * 65)

print(
    "Unique text groups:",
    len(group_df)
)


# ============================================================
# PART F — CHECK GROUP CATEGORY DISTRIBUTION
# ============================================================

print("\nCategory distribution among unique text groups:")

print(
    group_df["category"]
    .value_counts()
)


# ============================================================
# PART G — SPLIT UNIQUE TEXT GROUPS
# ============================================================

# IMPORTANT:
# We split TEXT GROUPS, not individual rows.
#
# Therefore, every occurrence of the same text will stay
# completely inside either train or validation.

train_groups, val_groups = train_test_split(
    group_df["text"],
    test_size=0.15,
    random_state=42,
    stratify=group_df["category"]
)


# ============================================================
# PART H — CREATE TRAIN AND VALIDATION DATAFRAMES
# ============================================================

train_df = df_clean[
    df_clean["text"].isin(train_groups)
].copy()

val_df = df_clean[
    df_clean["text"].isin(val_groups)
].copy()


# ============================================================
# PART I — RESET INDICES
# ============================================================

train_df = train_df.reset_index(drop=True)

val_df = val_df.reset_index(drop=True)


# ============================================================
# PART J — CHECK SPLIT SIZES
# ============================================================

print("\n" + "=" * 65)
print("FINAL TRAIN / VALIDATION SPLIT")
print("=" * 65)

print(
    "Training rows:",
    len(train_df)
)

print(
    "Validation rows:",
    len(val_df)
)

print(
    "Total:",
    len(train_df) + len(val_df)
)


# ============================================================
# PART K — CHECK TEXT OVERLAP
# ============================================================

train_texts = set(
    train_df["text"]
)

val_texts = set(
    val_df["text"]
)

overlap = train_texts.intersection(
    val_texts
)

print(
    "\nText groups appearing in BOTH train and validation:",
    len(overlap)
)


# ============================================================
# PART L — CHECK CATEGORY DISTRIBUTION
# ============================================================

print("\n" + "=" * 65)
print("TRAIN CATEGORY DISTRIBUTION")
print("=" * 65)

print(
    train_df["category"]
    .value_counts()
)


print("\n" + "=" * 65)
print("VALIDATION CATEGORY DISTRIBUTION")
print("=" * 65)

print(
    val_df["category"]
    .value_counts()
)


# ============================================================
# PART M — FINAL SANITY CHECK
# ============================================================

print("\n" + "=" * 65)
print("SANITY CHECK")
print("=" * 65)

print(
    "Train rows:",
    len(train_df)
)

print(
    "Validation rows:",
    len(val_df)
)

print(
    "Overlap:",
    len(overlap)
)

print(
    "Conflicting groups removed:",
    len(conflicting_texts)
)

=================================================================
CONFLICTING TEXTS
=================================================================
Number of conflicting text groups: 15

Conflicting texts:
['Amul butter', 'Courier', 'Family Mobile Service Provider recharge', 'Marathon', 'Mobile Service Provider recharge 365 days', 'Mobile Service Provider recharge wfh', 'Nariyal', 'To Family', 'audible subscription', 'flour mill', 'kindle unlimited', 'moscuito racket', 'reward Gpay', 'shoe polish', 'water jar']

=================================================================
AFTER REMOVING AMBIGUOUS TEXTS
=================================================================
Rows before: 1929
Rows after: 1855
Rows removed: 74

Remaining conflicting text groups: 0

=================================================================
UNIQUE TEXT GROUPS
=================================================================
Unique text groups: 1035

Category distribution among unique text groups:
category
Food              413
Transportation    185
Household         117
Other              86
Health             66
Apparel            33
Investment         27
Subscription       25
Family             20
Gift               16
Education          14
Leisure            12
Festivals          10
Beauty             10
Salary              1
Name: count, dtype: int64

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

In [11]:
# ============================================================
# STEP 10 — CORRECT LEAKAGE-SAFE TRAIN / VALIDATION SPLIT
# ============================================================

from sklearn.model_selection import train_test_split


# ============================================================
# 1. CHECK HOW MANY UNIQUE TEXT GROUPS EACH CATEGORY HAS
# ============================================================

group_category_counts = (
    group_df["category"]
    .value_counts()
    .sort_index()
)

print("=" * 65)
print("UNIQUE TEXT GROUPS PER CATEGORY")
print("=" * 65)

print(group_category_counts)


# ============================================================
# 2. FIND CATEGORIES WITH ONLY ONE UNIQUE TEXT GROUP
# ============================================================

singleton_categories = (
    group_category_counts[
        group_category_counts < 2
    ]
    .index
    .tolist()
)

print("\nCategories with fewer than 2 unique text groups:")

if singleton_categories:
    print(singleton_categories)
else:
    print("None")


# ============================================================
# 3. SEPARATE SINGLETON CATEGORIES
# ============================================================

singleton_groups = group_df[
    group_df["category"].isin(
        singleton_categories
    )
].copy()


splittable_groups = group_df[
    ~group_df["category"].isin(
        singleton_categories
    )
].copy()


print("\n" + "=" * 65)
print("GROUP SPLITTING DATA")
print("=" * 65)

print(
    "Splittable text groups:",
    len(splittable_groups)
)

print(
    "Singleton text groups:",
    len(singleton_groups)
)


# ============================================================
# 4. STRATIFIED SPLIT FOR CATEGORIES WITH ENOUGH GROUPS
# ============================================================

train_groups, val_groups = train_test_split(
    splittable_groups["text"],
    test_size=0.15,
    random_state=42,
    stratify=splittable_groups["category"]
)


# ============================================================
# 5. FORCE SINGLETON GROUPS INTO TRAINING
# ============================================================

singleton_texts = set(
    singleton_groups["text"]
)


train_groups = list(train_groups) + list(
    singleton_texts
)

val_groups = list(val_groups)


# ============================================================
# 6. BUILD FINAL TRAIN / VALIDATION DATAFRAMES
# ============================================================

train_df = df_clean[
    df_clean["text"].isin(train_groups)
].copy()

val_df = df_clean[
    df_clean["text"].isin(val_groups)
].copy()


train_df = train_df.reset_index(
    drop=True
)

val_df = val_df.reset_index(
    drop=True
)


# ============================================================
# 7. CHECK DATA SIZES
# ============================================================

print("\n" + "=" * 65)
print("FINAL TRAIN / VALIDATION SPLIT")
print("=" * 65)

print(
    "Training rows:",
    len(train_df)
)

print(
    "Validation rows:",
    len(val_df)
)

print(
    "Total rows:",
    len(train_df) + len(val_df)
)


# ============================================================
# 8. CHECK TEXT LEAKAGE
# ============================================================

train_texts = set(
    train_df["text"]
)

val_texts = set(
    val_df["text"]
)

overlap = train_texts.intersection(
    val_texts
)

print("\nText groups appearing in BOTH sets:")

print(
    len(overlap)
)


# ============================================================
# 9. TRAIN CATEGORY DISTRIBUTION
# ============================================================

print("\n" + "=" * 65)
print("TRAIN CATEGORY DISTRIBUTION")
print("=" * 65)

print(
    train_df["category"]
    .value_counts()
)


# ============================================================
# 10. VALIDATION CATEGORY DISTRIBUTION
# ============================================================

print("\n" + "=" * 65)
print("VALIDATION CATEGORY DISTRIBUTION")
print("=" * 65)

print(
    val_df["category"]
    .value_counts()
)


# ============================================================
# 11. CHECK WHICH CATEGORIES ARE IN VALIDATION
# ============================================================

train_categories = set(
    train_df["category"]
)

val_categories = set(
    val_df["category"]
)

print("\n" + "=" * 65)
print("CATEGORY COVERAGE")
print("=" * 65)

print(
    "Categories in training:",
    len(train_categories)
)

print(
    "Categories in validation:",
    len(val_categories)
)

print(
    "Categories only in training:",
    sorted(
        train_categories - val_categories
    )
)

print(
    "Categories only in validation:",
    sorted(
        val_categories - train_categories
    )
)


# ============================================================
# 12. FINAL SANITY CHECK
# ============================================================

print("\n" + "=" * 65)
print("FINAL SANITY CHECK")
print("=" * 65)

print(
    "Conflicting text groups removed:",
    len(conflicting_texts)
)

print(
    "Train/validation text overlap:",
    len(overlap)
)

print(
    "Singleton categories forced into train:",
    singleton_categories
)

=================================================================
UNIQUE TEXT GROUPS PER CATEGORY
=================================================================
category
Apparel            33
Beauty             10
Education          14
Family             20
Festivals          10
Food              413
Gift               16
Health             66
Household         117
Investment         27
Leisure            12
Other              86
Salary              1
Subscription       25
Transportation    185
Name: count, dtype: int64

Categories with fewer than 2 unique text groups:
['Salary']

=================================================================
GROUP SPLITTING DATA
=================================================================
Splittable text groups: 1034
Singleton text groups: 1

=================================================================
FINAL TRAIN / VALIDATION SPLIT
=================================================================
Training rows: 1601
Validation rows: 254
Total rows: 1855

Text groups appearing in BOTH sets:
0

=================================================================
TRAIN CATEGORY DISTRIBUTION
=================================================================
category
Food              726
Transportation    250
Household         135
Other              98
Investment         78
Health             71
Subscription       64
Salary             43
Apparel            38
Beauty             20
Gift               19
Family             18
Festivals          14
Education          14
Leisure            13
Name: count, dtype: int64

=================================================================
VALIDATION CATEGORY DISTRIBUTION
=================================================================
category
Food              98
Transportation    52
Household         25
Health            16
Other             14
Gift              10
Investment        10
Apparel            8
Beauty             5
Subscription       4
Family             4
Leisure            3
Education          3
Festivals          2
Name: count, dtype: int64

=================================================================
CATEGORY COVERAGE
=================================================================
Categories in training: 15
Categories in validation: 14
Categories only in training: ['Salary']
Categories only in validation: []

=================================================================
FINAL SANITY CHECK
=================================================================
Conflicting text groups removed: 15
Train/validation text overlap: 0
Singleton categories forced into train: ['Salary']

In [12]:
# ============================================================
# STEP 11 — MuRIL TOKEN LENGTH ANALYSIS
# ============================================================

!pip -q install transformers

from transformers import AutoTokenizer
import numpy as np


# ============================================================
# 1. LOAD MuRIL TOKENIZER
# ============================================================

MODEL_NAME = "google/muril-base-cased"

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

print("MuRIL tokenizer loaded successfully!")


# ============================================================
# 2. COMBINE TRAIN + VALIDATION TEXTS
# ============================================================

all_texts = pd.concat(
    [
        train_df["text"],
        val_df["text"]
    ],
    ignore_index=True
).astype(str)


print("\nTotal texts analyzed:")
print(len(all_texts))


# ============================================================
# 3. CALCULATE TOKEN LENGTHS
# ============================================================

token_lengths = []

for text in all_texts:

    tokens = tokenizer(
        text,
        truncation=False,
        add_special_tokens=True
    )

    token_lengths.append(
        len(tokens["input_ids"])
    )


token_lengths = np.array(
    token_lengths
)


# ============================================================
# 4. BASIC STATISTICS
# ============================================================

print("\n" + "=" * 65)
print("TOKEN LENGTH STATISTICS")
print("=" * 65)

print(
    "Minimum:",
    token_lengths.min()
)

print(
    "Maximum:",
    token_lengths.max()
)

print(
    "Mean:",
    round(
        token_lengths.mean(),
        2
    )
)

print(
    "Median:",
    np.median(token_lengths)
)

print(
    "95th percentile:",
    np.percentile(
        token_lengths,
        95
    )
)

print(
    "99th percentile:",
    np.percentile(
        token_lengths,
        99
    )
)


# ============================================================
# 5. CHECK COVERAGE FOR COMMON MAX_LENGTH VALUES
# ============================================================

print("\n" + "=" * 65)
print("MAX LENGTH COVERAGE")
print("=" * 65)

for max_len in [
    16,
    24,
    32,
    48,
    64
]:

    covered = (
        token_lengths <= max_len
    ).mean() * 100

    truncated = (
        token_lengths > max_len
    ).sum()

    print(
        f"MAX_LENGTH={max_len:2d}  | "
        f"Coverage={covered:6.2f}% | "
        f"Texts truncated={truncated}"
    )


# ============================================================
# 6. SHOW THE LONGEST TRANSACTIONS
# ============================================================

length_df = pd.DataFrame(
    {
        "text": all_texts,
        "token_length": token_lengths
    }
)

print("\n" + "=" * 65)
print("LONGEST TRANSACTION TEXTS")
print("=" * 65)

display(
    length_df
    .sort_values(
        "token_length",
        ascending=False
    )
    .head(20)
)


# ============================================================
# 7. SELECT A PRACTICAL MAX_LENGTH
# ============================================================

# We will choose after looking at the output.

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/411 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/206 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/113 [00:00<?, ?B/s]

MuRIL tokenizer loaded successfully!

Total texts analyzed:
1855

=================================================================
TOKEN LENGTH STATISTICS
=================================================================
Minimum: 3
Maximum: 32
Mean: 6.63
Median: 6.0
95th percentile: 13.0
99th percentile: 20.0

=================================================================
MAX LENGTH COVERAGE
=================================================================
MAX_LENGTH=16  | Coverage= 98.06% | Texts truncated=36
MAX_LENGTH=24  | Coverage= 99.51% | Texts truncated=9
MAX_LENGTH=32  | Coverage=100.00% | Texts truncated=0
MAX_LENGTH=48  | Coverage=100.00% | Texts truncated=0
MAX_LENGTH=64  | Coverage=100.00% | Texts truncated=0

=================================================================
LONGEST TRANSACTION TEXTS
=================================================================

                                                   text  token_length
1765  ( pav bhaji + 2 extra pav + sabudana khichdi +...            32
743   Laptop repair ( 128gb SSD rs 2200+ 500gb HDD R...            29
1347  flowers (.5kg)+sweets (.25gm+10/-)+vegetables ...            27
1181  3 parathe , 1 Hara bhara kabab, 1 rabdi malai,...            27
778   1 dal makhani rice(200)+ 1 chicken tikka rice(...            26
886   3 kg ( 2kg bajari Rs 7 each + 1kg gahu & maka ...            25
760   Tata sky STB (1299)+ 1 month recharge (226)+ e...            25
1821  bread (10)+Cadbury(10)+ cheese + myvaneese+pav...            25
954   milk 1 lit (64) + paneer (75) + bread (30) + 6...            25
771   Gehu 3 kg Rs21 + bajari 1kg Rs 7 + dal 1.5 kg ...            24
794   2 Kg Onion 30/kg + 1 kg Potato 30/kg + Parle B...            24
75            Glucose D(50) + flora bc (40)+cyra 20(10)            23
519   Home Food Delivery - roti 17*4+ paneer chatpat...            22
1189  Puja saman (150 for 5 Nariyal, 400 for 1kg swe...            22
974   Laptop repair (servicing+ 2gb ram upgrade + fa...            21
117   2 Thyroid (1000) + cholesterol (220) + uric ac...            21
689   roof top lounge  (200 french fries + 100 masal...            21
691   Jaipuri handprinted Maharani Saree (1850 Two p...            21
527   Home Food Delivery - Chicken lollypop 8 pcs 19...            20
1104       Himalaya soap(30) + Sofie (59) + kitkat (10)            20

In [13]:
# ============================================================
# STEP 12 — CREATE PYTORCH DATASET AND DATALOADERS
# ============================================================

import torch
from torch.utils.data import Dataset, DataLoader


# ============================================================
# 1. SETTINGS
# ============================================================

MAX_LENGTH = 32
BATCH_SIZE = 16


# ============================================================
# 2. CREATE DATASET CLASS
# ============================================================

class TransactionDataset(Dataset):

    def __init__(
        self,
        dataframe,
        tokenizer,
        max_length=32
    ):

        self.data = dataframe.reset_index(
            drop=True
        )

        self.tokenizer = tokenizer
        self.max_length = max_length


    def __len__(self):

        return len(self.data)


    def __getitem__(self, idx):

        # ----------------------------------------------------
        # Get transaction text
        # ----------------------------------------------------

        text = str(
            self.data.loc[
                idx,
                "text"
            ]
        )


        # ----------------------------------------------------
        # Tokenize text using MuRIL tokenizer
        # ----------------------------------------------------

        encoding = self.tokenizer(
            text,
            truncation=True,
            padding="max_length",
            max_length=self.max_length,
            return_tensors="pt"
        )


        # Remove batch dimension
        input_ids = encoding[
            "input_ids"
        ].squeeze(0)

        attention_mask = encoding[
            "attention_mask"
        ].squeeze(0)


        # ----------------------------------------------------
        # Get numerical labels
        # ----------------------------------------------------

        type_label = torch.tensor(
            self.data.loc[
                idx,
                "type_id"
            ],
            dtype=torch.long
        )

        category_label = torch.tensor(
            self.data.loc[
                idx,
                "category_id"
            ],
            dtype=torch.long
        )


        # ----------------------------------------------------
        # Return everything needed by the model
        # ----------------------------------------------------

        return {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "type_label": type_label,
            "category_label": category_label
        }


# ============================================================
# 3. CREATE TRAINING DATASET
# ============================================================

train_dataset = TransactionDataset(
    train_df,
    tokenizer,
    MAX_LENGTH
)


# ============================================================
# 4. CREATE VALIDATION DATASET
# ============================================================

val_dataset = TransactionDataset(
    val_df,
    tokenizer,
    MAX_LENGTH
)


print("=" * 65)
print("DATASET OBJECTS")
print("=" * 65)

print(
    "Training dataset size:",
    len(train_dataset)
)

print(
    "Validation dataset size:",
    len(val_dataset)
)


# ============================================================
# 5. SANITY CHECK ONE SAMPLE
# ============================================================

sample = train_dataset[0]

print("\n" + "=" * 65)
print("SAMPLE DATASET ITEM")
print("=" * 65)

print(
    "Input IDs shape:",
    sample["input_ids"].shape
)

print(
    "Attention mask shape:",
    sample["attention_mask"].shape
)

print(
    "Type label:",
    sample["type_label"].item()
)

print(
    "Category label:",
    sample["category_label"].item()
)


# ============================================================
# 6. CREATE TRAINING DATALOADER
# ============================================================

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2,
    pin_memory=torch.cuda.is_available()
)


# ============================================================
# 7. CREATE VALIDATION DATALOADER
# ============================================================

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=torch.cuda.is_available()
)


# ============================================================
# 8. CHECK NUMBER OF BATCHES
# ============================================================

print("\n" + "=" * 65)
print("DATALOADERS")
print("=" * 65)

print(
    "Batch size:",
    BATCH_SIZE
)

print(
    "Training batches:",
    len(train_loader)
)

print(
    "Validation batches:",
    len(val_loader)
)


# ============================================================
# 9. CHECK ONE ACTUAL BATCH
# ============================================================

batch = next(
    iter(train_loader)
)

print("\n" + "=" * 65)
print("ONE TRAINING BATCH")
print("=" * 65)

print(
    "input_ids:",
    batch["input_ids"].shape
)

print(
    "attention_mask:",
    batch["attention_mask"].shape
)

print(
    "type_label:",
    batch["type_label"].shape
)

print(
    "category_label:",
    batch["category_label"].shape
)

=================================================================
DATASET OBJECTS
=================================================================
Training dataset size: 1601
Validation dataset size: 254

=================================================================
SAMPLE DATASET ITEM
=================================================================
Input IDs shape: torch.Size([32])
Attention mask shape: torch.Size([32])
Type label: 0
Category label: 5

=================================================================
DATALOADERS
=================================================================
Batch size: 16
Training batches: 101
Validation batches: 16

=================================================================
ONE TRAINING BATCH
=================================================================
input_ids: torch.Size([16, 32])
attention_mask: torch.Size([16, 32])
type_label: torch.Size([16])
category_label: torch.Size([16])

In [14]:
# ============================================================
# STEP 13 — LOAD MuRIL AND BUILD CLASSIFIER
# ============================================================

import torch
import torch.nn as nn

from transformers import AutoModel


# ============================================================
# 1. MODEL NAME
# ============================================================

MODEL_NAME = "google/muril-base-cased"


# ============================================================
# 2. LOAD MuRIL BACKBONE
# ============================================================

print("Loading MuRIL...")

bert = AutoModel.from_pretrained(
    MODEL_NAME
)

print("MuRIL loaded successfully!")

print(
    "\nHidden size:",
    bert.config.hidden_size
)


# ============================================================
# 3. CREATE CLASSIFIER
# ============================================================

class TransactionClassifier(nn.Module):

    def __init__(
        self,
        bert_model,
        num_types,
        num_categories
    ):

        super().__init__()

        # MuRIL backbone
        self.bert = bert_model

        # MuRIL-base hidden size = 768
        hidden = self.bert.config.hidden_size

        # Dropout helps reduce overfitting
        self.dropout = nn.Dropout(0.1)

        # Type classification head
        # 768 → 2
        self.type_head = nn.Linear(
            hidden,
            num_types
        )

        # Category classification head
        # 768 → 15
        self.category_head = nn.Linear(
            hidden,
            num_categories
        )


    def forward(
        self,
        input_ids,
        attention_mask
    ):

        # Pass text through MuRIL
        output = self.bert(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        # Take MuRIL pooled representation
        pooled = output.pooler_output

        # Apply dropout
        pooled = self.dropout(
            pooled
        )

        # Make two predictions
        type_logits = self.type_head(
            pooled
        )

        category_logits = self.category_head(
            pooled
        )

        return (
            type_logits,
            category_logits
        )


# ============================================================
# 4. CREATE MODEL
# ============================================================

model = TransactionClassifier(
    bert_model=bert,
    num_types=len(type_labels),
    num_categories=len(category_labels)
)


# ============================================================
# 5. SELECT DEVICE
# ============================================================

device = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

model = model.to(device)


print("\n" + "=" * 65)
print("MODEL INFORMATION")
print("=" * 65)

print(
    "Device:",
    device
)

print(
    "Number of types:",
    len(type_labels)
)

print(
    "Number of categories:",
    len(category_labels)
)


# ============================================================
# 6. COUNT PARAMETERS
# ============================================================

total_params = sum(
    p.numel()
    for p in model.parameters()
)

bert_params = sum(
    p.numel()
    for p in model.bert.parameters()
)

head_params = (
    total_params
    - bert_params
)


print(
    "\nMuRIL parameters:",
    f"{bert_params:,}"
)

print(
    "Classification head parameters:",
    f"{head_params:,}"
)

print(
    "Total parameters:",
    f"{total_params:,}"
)


# ============================================================
# 7. CHECK TRAINABLE PARAMETERS
# ============================================================

trainable_params = sum(
    p.numel()
    for p in model.parameters()
    if p.requires_grad
)

print(
    "Trainable parameters:",
    f"{trainable_params:,}"
)


# ============================================================
# 8. TEST ONE BATCH
# ============================================================

model.eval()

with torch.no_grad():

    batch = next(
        iter(train_loader)
    )

    input_ids = batch[
        "input_ids"
    ].to(device)

    attention_mask = batch[
        "attention_mask"
    ].to(device)

    type_logits, category_logits = model(
        input_ids=input_ids,
        attention_mask=attention_mask
    )


print("\n" + "=" * 65)
print("FORWARD PASS TEST")
print("=" * 65)

print(
    "Input shape:",
    input_ids.shape
)

print(
    "Type logits shape:",
    type_logits.shape
)

print(
    "Category logits shape:",
    category_logits.shape
)

Loading MuRIL...

pytorch_model.bin:   0%|          | 0.00/953M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/953M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: google/muril-base-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
bert.embeddings.position_ids               | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

MuRIL loaded successfully!

Hidden size: 768

=================================================================
MODEL INFORMATION
=================================================================
Device: cuda
Number of types: 2
Number of categories: 15

MuRIL parameters: 237,556,224
Classification head parameters: 13,073
Total parameters: 237,569,297
Trainable parameters: 237,569,297

=================================================================
FORWARD PASS TEST
=================================================================
Input shape: torch.Size([16, 32])
Type logits shape: torch.Size([16, 2])
Category logits shape: torch.Size([16, 15])

In [15]:
# ============================================================
# STEP 14 — CALCULATE CATEGORY CLASS WEIGHTS
# ============================================================

import numpy as np
import torch

from sklearn.utils.class_weight import compute_class_weight


# ============================================================
# 1. GET TRAINING CATEGORY LABELS
# ============================================================

train_category_ids = (
    train_df["category_id"]
    .to_numpy()
)


# ============================================================
# 2. CREATE ALL CATEGORY IDS
# ============================================================

all_category_ids = np.arange(
    len(category_labels)
)


# ============================================================
# 3. CALCULATE BALANCED CLASS WEIGHTS
# ============================================================

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=all_category_ids,
    y=train_category_ids
)


# ============================================================
# 4. CONVERT TO PYTORCH TENSOR
# ============================================================

category_class_weights = torch.tensor(
    class_weights,
    dtype=torch.float32
).to(device)


# ============================================================
# 5. DISPLAY CATEGORY WEIGHTS
# ============================================================

print("=" * 65)
print("CATEGORY CLASS WEIGHTS")
print("=" * 65)

for category_id, category_name in enumerate(
    category_labels
):

    print(
        f"{category_id:2d} | "
        f"{category_name:15s} | "
        f"Train count = "
        f"{(train_category_ids == category_id).sum():3d} | "
        f"Weight = "
        f"{class_weights[category_id]:.4f}"
    )


# ============================================================
# 6. BASIC WEIGHT STATISTICS
# ============================================================

print("\n" + "=" * 65)
print("WEIGHT STATISTICS")
print("=" * 65)

print(
    "Minimum weight:",
    round(
        class_weights.min(),
        4
    )
)

print(
    "Maximum weight:",
    round(
        class_weights.max(),
        4
    )
)

print(
    "Mean weight:",
    round(
        class_weights.mean(),
        4
    )
)


# ============================================================
# 7. CHECK TENSOR
# ============================================================

print("\nPyTorch weight tensor:")

print(
    category_class_weights
)

=================================================================
CATEGORY CLASS WEIGHTS
=================================================================
 0 | Apparel         | Train count =  38 | Weight = 2.8088
 1 | Beauty          | Train count =  20 | Weight = 5.3367
 2 | Education       | Train count =  14 | Weight = 7.6238
 3 | Family          | Train count =  18 | Weight = 5.9296
 4 | Festivals       | Train count =  14 | Weight = 7.6238
 5 | Food            | Train count = 726 | Weight = 0.1470
 6 | Gift            | Train count =  19 | Weight = 5.6175
 7 | Health          | Train count =  71 | Weight = 1.5033
 8 | Household       | Train count = 135 | Weight = 0.7906
 9 | Investment      | Train count =  78 | Weight = 1.3684
10 | Leisure         | Train count =  13 | Weight = 8.2103
11 | Other           | Train count =  98 | Weight = 1.0891
12 | Salary          | Train count =  43 | Weight = 2.4822
13 | Subscription    | Train count =  64 | Weight = 1.6677
14 | Transportation  | Train count = 250 | Weight = 0.4269

=================================================================
WEIGHT STATISTICS
=================================================================
Minimum weight: 0.147
Maximum weight: 8.2103
Mean weight: 3.5084

PyTorch weight tensor:
tensor([2.8088, 5.3367, 7.6238, 5.9296, 7.6238, 0.1470, 5.6175, 1.5033, 0.7906,
        1.3684, 8.2103, 1.0891, 2.4822, 1.6677, 0.4269], device='cuda:0')

In [16]:
# ============================================================
# STEP 15 — LOSS FUNCTIONS + OPTIMIZER
# ============================================================

import torch
import torch.nn as nn


# ============================================================
# 1. TYPE LOSS
# ============================================================

# Type has only 2 classes:
# 0 = Expense
# 1 = Income

type_loss_fn = nn.CrossEntropyLoss()


# ============================================================
# 2. CATEGORY LOSS
# ============================================================

# Category loss uses our balanced class weights.
# This gives more importance to rare categories.

category_loss_fn = nn.CrossEntropyLoss(
    weight=category_class_weights
)


# ============================================================
# 3. OPTIMIZER
# ============================================================

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=2e-5
)


# ============================================================
# 4. DISPLAY SETTINGS
# ============================================================

print("=" * 65)
print("TRAINING CONFIGURATION")
print("=" * 65)

print(
    "Type loss:",
    "CrossEntropyLoss"
)

print(
    "Category loss:",
    "Weighted CrossEntropyLoss"
)

print(
    "Optimizer:",
    "AdamW"
)

print(
    "Learning rate:",
    2e-5
)


# ============================================================
# 5. TEST THE LOSS FUNCTIONS ON ONE BATCH
# ============================================================

model.train()

batch = next(
    iter(train_loader)
)

input_ids = batch[
    "input_ids"
].to(
    device,
    non_blocking=True
)

attention_mask = batch[
    "attention_mask"
].to(
    device,
    non_blocking=True
)

type_ids = batch[
    "type_label"
].to(
    device,
    non_blocking=True
)

category_ids = batch[
    "category_label"
].to(
    device,
    non_blocking=True
)


# ------------------------------------------------------------
# Clear previous gradients
# ------------------------------------------------------------

optimizer.zero_grad()


# ------------------------------------------------------------
# Forward pass
# ------------------------------------------------------------

type_logits, category_logits = model(
    input_ids,
    attention_mask
)


# ------------------------------------------------------------
# Calculate individual losses
# ------------------------------------------------------------

type_loss = type_loss_fn(
    type_logits,
    type_ids
)

category_loss = category_loss_fn(
    category_logits,
    category_ids
)


# ------------------------------------------------------------
# Combine losses
# ------------------------------------------------------------

total_loss = (
    type_loss
    + category_loss
)


# ============================================================
# 6. DISPLAY TEST RESULTS
# ============================================================

print("\n" + "=" * 65)
print("ONE BATCH LOSS TEST")
print("=" * 65)

print(
    "Type loss:",
    round(
        type_loss.item(),
        4
    )
)

print(
    "Category loss:",
    round(
        category_loss.item(),
        4
    )
)

print(
    "Total loss:",
    round(
        total_loss.item(),
        4
    )
)

=================================================================
TRAINING CONFIGURATION
=================================================================
Type loss: CrossEntropyLoss
Category loss: Weighted CrossEntropyLoss
Optimizer: AdamW
Learning rate: 2e-05

=================================================================
ONE BATCH LOSS TEST
=================================================================
Type loss: 0.7044
Category loss: 2.6973
Total loss: 3.4017

In [17]:
# ============================================================
# STEP 16 — TRAIN MuRIL
# ============================================================

import time
import torch


# ============================================================
# 1. TRAINING SETTINGS
# ============================================================

EPOCHS = 28

BEST_MODEL_PATH = (
    "/kaggle/working/"
    "muril_original_best.pt"
)

best_val_category_acc = 0.0


# ============================================================
# 2. TRAINING FUNCTION
# ============================================================

def train_one_epoch(
    model,
    loader,
    optimizer,
    device
):

    model.train()

    total_loss = 0.0

    correct_type = 0
    total_type = 0

    correct_category = 0
    total_category = 0


    for batch in loader:

        # ----------------------------------------------------
        # Move batch to GPU
        # ----------------------------------------------------

        input_ids = batch[
            "input_ids"
        ].to(
            device,
            non_blocking=True
        )

        attention_mask = batch[
            "attention_mask"
        ].to(
            device,
            non_blocking=True
        )

        type_ids = batch[
            "type_label"
        ].to(
            device,
            non_blocking=True
        )

        category_ids = batch[
            "category_label"
        ].to(
            device,
            non_blocking=True
        )


        # ----------------------------------------------------
        # Clear old gradients
        # ----------------------------------------------------

        optimizer.zero_grad()


        # ----------------------------------------------------
        # Forward pass
        # ----------------------------------------------------

        type_logits, category_logits = model(
            input_ids,
            attention_mask
        )


        # ----------------------------------------------------
        # Calculate losses
        # ----------------------------------------------------

        type_loss = type_loss_fn(
            type_logits,
            type_ids
        )

        category_loss = category_loss_fn(
            category_logits,
            category_ids
        )

        loss = (
            type_loss
            + category_loss
        )


        # ----------------------------------------------------
        # Backpropagation
        # ----------------------------------------------------

        loss.backward()


        # ----------------------------------------------------
        # Update model
        # ----------------------------------------------------

        optimizer.step()


        # ----------------------------------------------------
        # Store loss
        # ----------------------------------------------------

        total_loss += loss.item()


        # ----------------------------------------------------
        # Type predictions
        # ----------------------------------------------------

        type_predictions = torch.argmax(
            type_logits,
            dim=1
        )


        # ----------------------------------------------------
        # Category predictions
        # ----------------------------------------------------

        category_predictions = torch.argmax(
            category_logits,
            dim=1
        )


        # ----------------------------------------------------
        # Count correct predictions
        # ----------------------------------------------------

        correct_type += (
            type_predictions == type_ids
        ).sum().item()

        total_type += (
            type_ids.size(0)
        )


        correct_category += (
            category_predictions == category_ids
        ).sum().item()

        total_category += (
            category_ids.size(0)
        )


    # ========================================================
    # EPOCH METRICS
    # ========================================================

    average_loss = (
        total_loss
        / len(loader)
    )

    type_accuracy = (
        correct_type
        / total_type
        * 100
    )

    category_accuracy = (
        correct_category
        / total_category
        * 100
    )

    return (
        average_loss,
        type_accuracy,
        category_accuracy
    )


# ============================================================
# 3. VALIDATION FUNCTION
# ============================================================

def validate(
    model,
    loader,
    device
):

    model.eval()

    total_loss = 0.0

    correct_type = 0
    total_type = 0

    correct_category = 0
    total_category = 0


    with torch.no_grad():

        for batch in loader:

            # ------------------------------------------------
            # Move batch to GPU
            # ------------------------------------------------

            input_ids = batch[
                "input_ids"
            ].to(
                device,
                non_blocking=True
            )

            attention_mask = batch[
                "attention_mask"
            ].to(
                device,
                non_blocking=True
            )

            type_ids = batch[
                "type_label"
            ].to(
                device,
                non_blocking=True
            )

            category_ids = batch[
                "category_label"
            ].to(
                device,
                non_blocking=True
            )


            # ------------------------------------------------
            # Forward pass
            # ------------------------------------------------

            type_logits, category_logits = model(
                input_ids,
                attention_mask
            )


            # ------------------------------------------------
            # Validation loss
            # ------------------------------------------------

            type_loss = type_loss_fn(
                type_logits,
                type_ids
            )

            category_loss = category_loss_fn(
                category_logits,
                category_ids
            )

            loss = (
                type_loss
                + category_loss
            )

            total_loss += loss.item()


            # ------------------------------------------------
            # Predictions
            # ------------------------------------------------

            type_predictions = torch.argmax(
                type_logits,
                dim=1
            )

            category_predictions = torch.argmax(
                category_logits,
                dim=1
            )


            # ------------------------------------------------
            # Accuracy
            # ------------------------------------------------

            correct_type += (
                type_predictions == type_ids
            ).sum().item()

            total_type += (
                type_ids.size(0)
            )

            correct_category += (
                category_predictions == category_ids
            ).sum().item()

            total_category += (
                category_ids.size(0)
            )


    average_loss = (
        total_loss
        / len(loader)
    )

    type_accuracy = (
        correct_type
        / total_type
        * 100
    )

    category_accuracy = (
        correct_category
        / total_category
        * 100
    )

    return (
        average_loss,
        type_accuracy,
        category_accuracy
    )


# ============================================================
# 4. TRAINING LOOP
# ============================================================

print("=" * 70)
print("STARTING MuRIL TRAINING")
print("=" * 70)

print(
    "Epochs:",
    EPOCHS
)

print(
    "Best model:",
    BEST_MODEL_PATH
)

print()


for epoch in range(EPOCHS):

    start_time = time.time()


    # --------------------------------------------------------
    # Training
    # --------------------------------------------------------

    train_loss, train_type_acc, train_category_acc = (
        train_one_epoch(
            model,
            train_loader,
            optimizer,
            device
        )
    )


    # --------------------------------------------------------
    # Validation
    # --------------------------------------------------------

    val_loss, val_type_acc, val_category_acc = (
        validate(
            model,
            val_loader,
            device
        )
    )


    # --------------------------------------------------------
    # Time
    # --------------------------------------------------------

    epoch_time = (
        time.time()
        - start_time
    )


    # --------------------------------------------------------
    # Print results
    # --------------------------------------------------------

    print(
        f"Epoch {epoch + 1:02d}/{EPOCHS} | "
        f"Train Loss: {train_loss:.4f} | "
        f"Train Type Acc: {train_type_acc:.2f}% | "
        f"Train Cat Acc: {train_category_acc:.2f}% | "
        f"Val Loss: {val_loss:.4f} | "
        f"Val Type Acc: {val_type_acc:.2f}% | "
        f"Val Cat Acc: {val_category_acc:.2f}% | "
        f"Time: {epoch_time:.1f}s"
    )


    # --------------------------------------------------------
    # Save best model
    # --------------------------------------------------------

    if val_category_acc > best_val_category_acc:

        best_val_category_acc = (
            val_category_acc
        )

        torch.save(
            model.state_dict(),
            BEST_MODEL_PATH
        )

        print(
            f"  --> NEW BEST MODEL SAVED "
            f"(Val Cat Acc: "
            f"{best_val_category_acc:.2f}%)"
        )

    else:

        print(
            f"  --> No improvement "
            f"(Best: "
            f"{best_val_category_acc:.2f}%)"
        )


# ============================================================
# 5. TRAINING COMPLETE
# ============================================================

print("\n" + "=" * 70)
print("TRAINING COMPLETE")
print("=" * 70)

print(
    "Best validation category accuracy:",
    f"{best_val_category_acc:.2f}%"
)

print(
    "Best model saved at:",
    BEST_MODEL_PATH
)

======================================================================
STARTING MuRIL TRAINING
======================================================================
Epochs: 28
Best model: /kaggle/working/muril_original_best.pt

Epoch 01/28 | Train Loss: 3.2802 | Train Type Acc: 86.07% | Train Cat Acc: 27.61% | Val Loss: 3.1227 | Val Type Acc: 98.82% | Val Cat Acc: 38.58% | Time: 16.3s
  --> NEW BEST MODEL SAVED (Val Cat Acc: 38.58%)
Epoch 02/28 | Train Loss: 3.0397 | Train Type Acc: 94.38% | Train Cat Acc: 44.53% | Val Loss: 2.9041 | Val Type Acc: 98.82% | Val Cat Acc: 38.58% | Time: 16.3s
  --> No improvement (Best: 38.58%)
Epoch 03/28 | Train Loss: 2.8867 | Train Type Acc: 94.38% | Train Cat Acc: 39.41% | Val Loss: 2.8029 | Val Type Acc: 98.82% | Val Cat Acc: 38.58% | Time: 16.4s
  --> No improvement (Best: 38.58%)
Epoch 04/28 | Train Loss: 2.7719 | Train Type Acc: 97.94% | Train Cat Acc: 45.97% | Val Loss: 2.7378 | Val Type Acc: 99.61% | Val Cat Acc: 38.58% | Time: 16.5s
  --> No improvement (Best: 38.58%)
Epoch 05/28 | Train Loss: 2.6812 | Train Type Acc: 98.94% | Train Cat Acc: 43.85% | Val Loss: 2.6827 | Val Type Acc: 99.21% | Val Cat Acc: 38.58% | Time: 16.3s
  --> No improvement (Best: 38.58%)
Epoch 06/28 | Train Loss: 2.6174 | Train Type Acc: 99.38% | Train Cat Acc: 39.85% | Val Loss: 2.6245 | Val Type Acc: 100.00% | Val Cat Acc: 44.09% | Time: 16.2s
  --> NEW BEST MODEL SAVED (Val Cat Acc: 44.09%)
Epoch 07/28 | Train Loss: 2.5301 | Train Type Acc: 99.56% | Train Cat Acc: 39.98% | Val Loss: 2.5599 | Val Type Acc: 100.00% | Val Cat Acc: 43.70% | Time: 16.2s
  --> No improvement (Best: 44.09%)
Epoch 08/28 | Train Loss: 2.4375 | Train Type Acc: 99.56% | Train Cat Acc: 51.72% | Val Loss: 2.5056 | Val Type Acc: 100.00% | Val Cat Acc: 43.31% | Time: 16.3s
  --> No improvement (Best: 44.09%)
Epoch 09/28 | Train Loss: 2.3588 | Train Type Acc: 99.88% | Train Cat Acc: 53.72% | Val Loss: 2.4089 | Val Type Acc: 100.00% | Val Cat Acc: 48.03% | Time: 16.4s
  --> NEW BEST MODEL SAVED (Val Cat Acc: 48.03%)
Epoch 10/28 | Train Loss: 2.2468 | Train Type Acc: 99.69% | Train Cat Acc: 58.28% | Val Loss: 2.3493 | Val Type Acc: 100.00% | Val Cat Acc: 68.90% | Time: 16.3s
  --> NEW BEST MODEL SAVED (Val Cat Acc: 68.90%)
Epoch 11/28 | Train Loss: 2.1069 | Train Type Acc: 99.69% | Train Cat Acc: 65.15% | Val Loss: 2.2193 | Val Type Acc: 100.00% | Val Cat Acc: 70.08% | Time: 16.3s
  --> NEW BEST MODEL SAVED (Val Cat Acc: 70.08%)
Epoch 12/28 | Train Loss: 1.9865 | Train Type Acc: 99.69% | Train Cat Acc: 72.89% | Val Loss: 2.1315 | Val Type Acc: 100.00% | Val Cat Acc: 71.65% | Time: 16.3s
  --> NEW BEST MODEL SAVED (Val Cat Acc: 71.65%)
Epoch 13/28 | Train Loss: 1.8379 | Train Type Acc: 99.69% | Train Cat Acc: 75.89% | Val Loss: 2.0225 | Val Type Acc: 100.00% | Val Cat Acc: 75.20% | Time: 16.4s
  --> NEW BEST MODEL SAVED (Val Cat Acc: 75.20%)
Epoch 14/28 | Train Loss: 1.6833 | Train Type Acc: 99.69% | Train Cat Acc: 81.64% | Val Loss: 2.1209 | Val Type Acc: 100.00% | Val Cat Acc: 69.29% | Time: 16.3s
  --> No improvement (Best: 75.20%)
Epoch 15/28 | Train Loss: 1.5172 | Train Type Acc: 99.63% | Train Cat Acc: 86.07% | Val Loss: 1.7610 | Val Type Acc: 100.00% | Val Cat Acc: 77.95% | Time: 16.3s
  --> NEW BEST MODEL SAVED (Val Cat Acc: 77.95%)
Epoch 16/28 | Train Loss: 1.3493 | Train Type Acc: 99.88% | Train Cat Acc: 88.94% | Val Loss: 1.6472 | Val Type Acc: 100.00% | Val Cat Acc: 82.68% | Time: 16.3s
  --> NEW BEST MODEL SAVED (Val Cat Acc: 82.68%)
Epoch 17/28 | Train Loss: 1.1698 | Train Type Acc: 99.75% | Train Cat Acc: 91.51% | Val Loss: 1.5903 | Val Type Acc: 100.00% | Val Cat Acc: 83.46% | Time: 16.3s
  --> NEW BEST MODEL SAVED (Val Cat Acc: 83.46%)
Epoch 18/28 | Train Loss: 1.0017 | Train Type Acc: 99.75% | Train Cat Acc: 94.63% | Val Loss: 1.4629 | Val Type Acc: 100.00% | Val Cat Acc: 78.74% | Time: 16.4s
  --> No improvement (Best: 83.46%)
Epoch 19/28 | Train Loss: 0.8329 | Train Type Acc: 99.81% | Train Cat Acc: 95.88% | Val Loss: 1.4235 | Val Type Acc: 100.00% | Val Cat Acc: 79.92% | Time: 16.3s
  --> No improvement (Best: 83.46%)
Epoch 20/28 | Train Loss: 0.7045 | Train Type Acc: 99.81% | Train Cat Acc: 96.88% | Val Loss: 1.3697 | Val Type Acc: 100.00% | Val Cat Acc: 81.89% | Time: 16.3s
  --> No improvement (Best: 83.46%)
Epoch 21/28 | Train Loss: 0.5872 | Train Type Acc: 100.00% | Train Cat Acc: 96.13% | Val Loss: 1.2817 | Val Type Acc: 100.00% | Val Cat Acc: 78.35% | Time: 16.2s
  --> No improvement (Best: 83.46%)
Epoch 22/28 | Train Loss: 0.5002 | Train Type Acc: 99.94% | Train Cat Acc: 96.75% | Val Loss: 1.1969 | Val Type Acc: 100.00% | Val Cat Acc: 82.28% | Time: 16.3s
  --> No improvement (Best: 83.46%)
Epoch 23/28 | Train Loss: 0.3991 | Train Type Acc: 99.88% | Train Cat Acc: 98.44% | Val Loss: 1.2297 | Val Type Acc: 100.00% | Val Cat Acc: 77.95% | Time: 16.3s
  --> No improvement (Best: 83.46%)
Epoch 24/28 | Train Loss: 0.3348 | Train Type Acc: 99.88% | Train Cat Acc: 98.63% | Val Loss: 1.0778 | Val Type Acc: 100.00% | Val Cat Acc: 83.86% | Time: 16.3s
  --> NEW BEST MODEL SAVED (Val Cat Acc: 83.86%)
Epoch 25/28 | Train Loss: 0.2621 | Train Type Acc: 99.94% | Train Cat Acc: 99.25% | Val Loss: 1.1016 | Val Type Acc: 100.00% | Val Cat Acc: 80.71% | Time: 16.3s
  --> No improvement (Best: 83.86%)
Epoch 26/28 | Train Loss: 0.2127 | Train Type Acc: 100.00% | Train Cat Acc: 99.56% | Val Loss: 1.2664 | Val Type Acc: 100.00% | Val Cat Acc: 78.74% | Time: 16.3s
  --> No improvement (Best: 83.86%)
Epoch 27/28 | Train Loss: 0.1850 | Train Type Acc: 100.00% | Train Cat Acc: 98.63% | Val Loss: 1.1869 | Val Type Acc: 100.00% | Val Cat Acc: 84.65% | Time: 16.3s
  --> NEW BEST MODEL SAVED (Val Cat Acc: 84.65%)
Epoch 28/28 | Train Loss: 0.1671 | Train Type Acc: 100.00% | Train Cat Acc: 97.94% | Val Loss: 1.2406 | Val Type Acc: 100.00% | Val Cat Acc: 80.71% | Time: 16.3s
  --> No improvement (Best: 84.65%)

======================================================================
TRAINING COMPLETE
======================================================================
Best validation category accuracy: 84.65%
Best model saved at: /kaggle/working/muril_original_best.pt

In [18]:


# ============================================================
# STEP 17 — LOAD BEST MODEL + FULL EVALUATION
# ============================================================

import torch
import numpy as np
import pandas as pd

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score
)


# ============================================================
# 1. LOAD BEST CHECKPOINT
# ============================================================

BEST_MODEL_PATH = (
    "/kaggle/working/"
    "muril_original_best.pt"
)

model.load_state_dict(
    torch.load(
        BEST_MODEL_PATH,
        map_location=device
    )
)

model = model.to(device)

print(
    "Best checkpoint loaded successfully!"
)


# ============================================================
# 2. EVALUATION MODE
# ============================================================

model.eval()


# ============================================================
# 3. STORAGE FOR PREDICTIONS
# ============================================================

all_type_true = []
all_type_pred = []

all_category_true = []
all_category_pred = []


# ============================================================
# 4. RUN VALIDATION
# ============================================================

with torch.no_grad():

    for batch in val_loader:

        input_ids = batch[
            "input_ids"
        ].to(
            device,
            non_blocking=True
        )

        attention_mask = batch[
            "attention_mask"
        ].to(
            device,
            non_blocking=True
        )

        type_ids = batch[
            "type_label"
        ].to(
            device,
            non_blocking=True
        )

        category_ids = batch[
            "category_label"
        ].to(
            device,
            non_blocking=True
        )


        # Forward pass
        type_logits, category_logits = model(
            input_ids,
            attention_mask
        )


        # Predicted classes
        type_predictions = torch.argmax(
            type_logits,
            dim=1
        )

        category_predictions = torch.argmax(
            category_logits,
            dim=1
        )


        # Move predictions back to CPU
        all_type_true.extend(
            type_ids.cpu().numpy()
        )

        all_type_pred.extend(
            type_predictions.cpu().numpy()
        )

        all_category_true.extend(
            category_ids.cpu().numpy()
        )

        all_category_pred.extend(
            category_predictions.cpu().numpy()
        )


# ============================================================
# 5. CONVERT TO NUMPY
# ============================================================

all_type_true = np.array(
    all_type_true
)

all_type_pred = np.array(
    all_type_pred
)

all_category_true = np.array(
    all_category_true
)

all_category_pred = np.array(
    all_category_pred
)


# ============================================================
# 6. TYPE METRICS
# ============================================================

type_accuracy = accuracy_score(
    all_type_true,
    all_type_pred
)

type_macro_f1 = f1_score(
    all_type_true,
    all_type_pred,
    average="macro",
    zero_division=0
)


print("\n" + "=" * 70)
print("TYPE RESULTS")
print("=" * 70)

print(
    f"Type Accuracy: {type_accuracy * 100:.2f}%"
)

print(
    f"Type Macro-F1: {type_macro_f1:.4f}"
)


# ============================================================
# 7. CATEGORY METRICS
# ============================================================

category_accuracy = accuracy_score(
    all_category_true,
    all_category_pred
)

category_macro_f1 = f1_score(
    all_category_true,
    all_category_pred,
    average="macro",
    zero_division=0
)

category_weighted_f1 = f1_score(
    all_category_true,
    all_category_pred,
    average="weighted",
    zero_division=0
)


print("\n" + "=" * 70)
print("CATEGORY RESULTS")
print("=" * 70)

print(
    f"Category Accuracy: "
    f"{category_accuracy * 100:.2f}%"
)

print(
    f"Category Macro-F1: "
    f"{category_macro_f1:.4f}"
)

print(
    f"Category Weighted-F1: "
    f"{category_weighted_f1:.4f}"
)


# ============================================================
# 8. CLASSIFICATION REPORT
# ============================================================

print("\n" + "=" * 70)
print("CATEGORY CLASSIFICATION REPORT")
print("=" * 70)

print(
    classification_report(
        all_category_true,
        all_category_pred,
        labels=np.arange(
            len(category_labels)
        ),
        target_names=category_labels,
        zero_division=0
    )
)


# ============================================================
# 9. CONFUSION MATRIX
# ============================================================

category_cm = confusion_matrix(
    all_category_true,
    all_category_pred,
    labels=np.arange(
        len(category_labels)
    )
)

print("\n" + "=" * 70)
print("CATEGORY CONFUSION MATRIX")
print("=" * 70)

print(
    pd.DataFrame(
        category_cm,
        index=category_labels,
        columns=category_labels
    )
)


# ============================================================
# 10. PER-CATEGORY SUMMARY
# ============================================================

report_dict = classification_report(
    all_category_true,
    all_category_pred,
    labels=np.arange(
        len(category_labels)
    ),
    target_names=category_labels,
    output_dict=True,
    zero_division=0
)

per_category = pd.DataFrame(
    report_dict
).T

print("\n" + "=" * 70)
print("PER-CATEGORY F1")
print("=" * 70)

print(
    per_category[
        [
            "precision",
            "recall",
            "f1-score",
            "support"
        ]
    ]
    .to_string()
)

Best checkpoint loaded successfully!

======================================================================
TYPE RESULTS
======================================================================
Type Accuracy: 100.00%
Type Macro-F1: 1.0000

======================================================================
CATEGORY RESULTS
======================================================================
Category Accuracy: 84.65%
Category Macro-F1: 0.7113
Category Weighted-F1: 0.8369

======================================================================
CATEGORY CLASSIFICATION REPORT
======================================================================
                precision    recall  f1-score   support

       Apparel       0.86      0.75      0.80         8
        Beauty       0.83      1.00      0.91         5
     Education       1.00      1.00      1.00         3
        Family       0.00      0.00      0.00         4
     Festivals       1.00      1.00      1.00         2
          Food       0.94      0.96      0.95        98
          Gift       0.90      0.90      0.90        10
        Health       0.82      0.56      0.67        16
     Household       0.59      0.68      0.63        25
    Investment       1.00      1.00      1.00        10
       Leisure       0.00      0.00      0.00         3
         Other       0.38      0.43      0.40        14
        Salary       0.00      0.00      0.00         0
  Subscription       0.75      0.75      0.75         4
Transportation       0.93      0.98      0.95        52

      accuracy                           0.85       254
     macro avg       0.67      0.67      0.66       254
  weighted avg       0.83      0.85      0.84       254


======================================================================
CATEGORY CONFUSION MATRIX
======================================================================
                Apparel  Beauty  Education  Family  Festivals  Food  Gift  \
Apparel               6       0          0       0          0     0     0
Beauty                0       5          0       0          0     0     0
Education             0       0          3       0          0     0     0
Family                0       1          0       0          0     0     0
Festivals             0       0          0       0          2     0     0
Food                  0       0          0       0          0    94     0
Gift                  0       0          0       0          0     0     9
Health                0       0          0       0          0     1     0
Household             1       0          0       1          0     3     0
Investment            0       0          0       0          0     0     0
Leisure               0       0          0       0          0     0     0
Other                 0       0          0       0          0     2     1
Salary                0       0          0       0          0     0     0
Subscription          0       0          0       0          0     0     0
Transportation        0       0          0       0          0     0     0

                Health  Household  Investment  Leisure  Other  Salary  \
Apparel              1          1           0        0      0       0
Beauty               0          0           0        0      0       0
Education            0          0           0        0      0       0
Family               0          1           0        0      2       0
Festivals            0          0           0        0      0       0
Food                 0          4           0        0      0       0
Gift                 0          1           0        0      0       0
Health               9          1           0        0      5       0
Household            1         17           0        0      2       0
Investment           0          0          10        0      0       0
Leisure              0          1           0        0      0       0
Other                0          2           0        0      6       0
Salary               0          0           0        0      0       0
Subscription         0          0           0        0      1       0
Transportation       0          1           0        0      0       0

                Subscription  Transportation
Apparel                    0               0
Beauty                     0               0
Education                  0               0
Family                     0               0
Festivals                  0               0
Food                       0               0
Gift                       0               0
Health                     0               0
Household                  0               0
Investment                 0               0
Leisure                    0               2
Other                      1               2
Salary                     0               0
Subscription               3               0
Transportation             0              51

======================================================================
PER-CATEGORY F1
======================================================================
                precision    recall  f1-score     support
Apparel          0.857143  0.750000  0.800000    8.000000
Beauty           0.833333  1.000000  0.909091    5.000000
Education        1.000000  1.000000  1.000000    3.000000
Family           0.000000  0.000000  0.000000    4.000000
Festivals        1.000000  1.000000  1.000000    2.000000
Food             0.940000  0.959184  0.949495   98.000000
Gift             0.900000  0.900000  0.900000   10.000000
Health           0.818182  0.562500  0.666667   16.000000
Household        0.586207  0.680000  0.629630   25.000000
Investment       1.000000  1.000000  1.000000   10.000000
Leisure          0.000000  0.000000  0.000000    3.000000
Other            0.375000  0.428571  0.400000   14.000000
Salary           0.000000  0.000000  0.000000    0.000000
Subscription     0.750000  0.750000  0.750000    4.000000
Transportation   0.927273  0.980769  0.953271   52.000000
accuracy         0.846457  0.846457  0.846457    0.846457
macro avg        0.665809  0.667402  0.663877  254.000000
weighted avg     0.832118  0.846457  0.836903  254.000000

In [19]:
# ============================================================
# STEP 18 — ERROR ANALYSIS
# ============================================================

import torch
import pandas as pd
import numpy as np


# ============================================================
# 1. MAKE SURE BEST MODEL IS LOADED
# ============================================================

BEST_MODEL_PATH = (
    "/kaggle/working/"
    "muril_original_best.pt"
)

model.load_state_dict(
    torch.load(
        BEST_MODEL_PATH,
        map_location=device
    )
)

model.to(device)
model.eval()


# ============================================================
# 2. COLLECT PREDICTIONS + CONFIDENCE
# ============================================================

prediction_rows = []

row_position = 0


with torch.no_grad():

    for batch in val_loader:

        input_ids = batch[
            "input_ids"
        ].to(
            device,
            non_blocking=True
        )

        attention_mask = batch[
            "attention_mask"
        ].to(
            device,
            non_blocking=True
        )


        # Forward pass
        type_logits, category_logits = model(
            input_ids,
            attention_mask
        )


        # Convert logits to probabilities
        category_probs = torch.softmax(
            category_logits,
            dim=1
        )


        # Get prediction + confidence
        category_confidence, category_prediction = (
            torch.max(
                category_probs,
                dim=1
            )
        )


        # Move to CPU
        category_prediction = (
            category_prediction
            .cpu()
            .numpy()
        )

        category_confidence = (
            category_confidence
            .cpu()
            .numpy()
        )


        # Store predictions
        for i in range(
            len(category_prediction)
        ):

            actual_id = int(
                val_df.iloc[
                    row_position,
                    : 
                ]["category_id"]
            )

            predicted_id = int(
                category_prediction[i]
            )

            confidence = float(
                category_confidence[i]
            )

            prediction_rows.append(
                {
                    "text": val_df.iloc[
                        row_position
                    ]["text"],

                    "actual": category_labels[
                        actual_id
                    ],

                    "predicted": category_labels[
                        predicted_id
                    ],

                    "confidence": confidence,

                    "actual_id": actual_id,

                    "predicted_id": predicted_id
                }
            )

            row_position += 1


# ============================================================
# 3. CREATE RESULTS DATAFRAME
# ============================================================

results_df = pd.DataFrame(
    prediction_rows
)


# ============================================================
# 4. MARK CORRECT / INCORRECT
# ============================================================

results_df["correct"] = (
    results_df["actual_id"]
    ==
    results_df["predicted_id"]
)


# ============================================================
# 5. SHOW BASIC COUNTS
# ============================================================

print("=" * 70)
print("ERROR ANALYSIS SUMMARY")
print("=" * 70)

print(
    "Validation examples:",
    len(results_df)
)

print(
    "Correct:",
    results_df["correct"].sum()
)

print(
    "Incorrect:",
    (~results_df["correct"]).sum()
)


# ============================================================
# 6. SHOW ALL MISCLASSIFIED EXAMPLES
# ============================================================

errors_df = results_df[
    ~results_df["correct"]
].copy()

print("\n" + "=" * 70)
print("MISCLASSIFIED TRANSACTIONS")
print("=" * 70)

display(
    errors_df[
        [
            "text",
            "actual",
            "predicted",
            "confidence"
        ]
    ]
    .sort_values(
        "confidence",
        ascending=False
    )
)


# ============================================================
# 7. MOST COMMON CONFUSION PAIRS
# ============================================================

print("\n" + "=" * 70)
print("MOST COMMON CONFUSION PAIRS")
print("=" * 70)

confusion_pairs = (
    errors_df
    .groupby(
        [
            "actual",
            "predicted"
        ]
    )
    .size()
    .reset_index(
        name="count"
    )
    .sort_values(
        "count",
        ascending=False
    )
)

print(
    confusion_pairs.to_string(
        index=False
    )
)


# ============================================================
# 8. LOW-CONFIDENCE CORRECT PREDICTIONS
# ============================================================

print("\n" + "=" * 70)
print("LOW-CONFIDENCE CORRECT PREDICTIONS")
print("=" * 70)

low_conf_correct = results_df[
    results_df["correct"]
].sort_values(
    "confidence"
).head(20)

display(
    low_conf_correct[
        [
            "text",
            "actual",
            "confidence"
        ]
    ]
)


# ============================================================
# 9. WRONG PREDICTIONS BY ACTUAL CATEGORY
# ============================================================

print("\n" + "=" * 70)
print("ERRORS BY ACTUAL CATEGORY")
print("=" * 70)

errors_by_actual = (
    errors_df["actual"]
    .value_counts()
)

print(
    errors_by_actual
)


# ============================================================
# 10. WRONG PREDICTIONS BY PREDICTED CATEGORY
# ============================================================

print("\n" + "=" * 70)
print("ERRORS BY PREDICTED CATEGORY")
print("=" * 70)

errors_by_predicted = (
    errors_df["predicted"]
    .value_counts()
)

print(
    errors_by_predicted
)

======================================================================
ERROR ANALYSIS SUMMARY
======================================================================
Validation examples: 254
Correct: 215
Incorrect: 39

======================================================================
MISCLASSIFIED TRANSACTIONS
======================================================================

,text,actual,predicted,confidence
243,deo and amul milk,Other,Food,0.924359
32,Soap + dahya pav kg,Household,Food,0.923904
227,Sapat Parivar Tea half kg,Household,Food,0.923748
85,Agarbatti 55 + dahi 25,Household,Food,0.923704
202,medicine,Health,Food,0.921568
1,HBR 2 Months subscription,Other,Subscription,0.907801
33,"Soap, shampoo, razor",Family,Beauty,0.907106
8,July salary,Household,Other,0.883932
75,Nandadip oil bottle,Household,Other,0.881603
88,Shopping at Alfa,Other,Transportation,0.873350
26,Shopping at Alfa,Other,Transportation,0.873350
235,toothbrush + biscuits,Food,Household,0.873238
105,clock cell,Other,Household,0.871737
34,Digilock room charges,Other,Household,0.870353
44,Pattice,Food,Household,0.869340
230,6 pairs of use and throw gloves,Health,Household,0.863902
117,Change,Family,Other,0.840183
81,Change,Family,Other,0.840183
203,Undated Planner - June shop,Family,Household,0.837609
231,Tambola,Other,Food,0.834214
199,carrets + brinjal + flower,Food,Household,0.831021
138,Crockery,Household,Apparel,0.819695
106,Odonil,Household,Health,0.810326
55,First servicing,Transportation,Household,0.788639
134,Cupcake mould,Gift,Household,0.767039
25,Mast & Harbour Slides,Apparel,Household,0.656566
154,To savings account,Other,Gift,0.579188
205,riverdine date,Food,Household,0.559174
145,March 210 + April 170,Subscription,Other,0.528264
136,Sanjori mould,Household,Family,0.514561
10,2 INOX,Leisure,Household,0.489447
229,belt + socs,Apparel,Health,0.438723
116,Tours and Travel,Leisure,Transportation,0.413738
122,Tours and Travel,Leisure,Transportation,0.413738
21,Doctor Fees,Health,Other,0.354102
100,Doctor Fees,Health,Other,0.354102
192,Doctor Fees,Health,Other,0.354102
166,Doctor Fees,Health,Other,0.354102
198,Doctor Fees,Health,Other,0.354102

======================================================================
MOST COMMON CONFUSION PAIRS
======================================================================
        actual      predicted  count
        Health          Other      5
          Food      Household      4
     Household           Food      3
        Family          Other      2
       Leisure Transportation      2
     Household          Other      2
         Other      Household      2
         Other Transportation      2
         Other           Food      2
          Gift      Household      1
        Health           Food      1
        Family      Household      1
       Apparel      Household      1
       Apparel         Health      1
        Family         Beauty      1
        Health      Household      1
       Leisure      Household      1
     Household         Health      1
     Household        Apparel      1
     Household         Family      1
         Other           Gift      1
         Other   Subscription      1
  Subscription          Other      1
Transportation      Household      1

======================================================================
LOW-CONFIDENCE CORRECT PREDICTIONS
======================================================================

                             text   actual  confidence
221           hand gloves 4 pairs   Health    0.492513
66   Pyjama (999)+ carry bag (10)  Apparel    0.635280
14              Cataract Medicine   Health    0.678511
13              Cataract Medicine   Health    0.678511
16              Cataract Medicine   Health    0.678511
191                   antibiotics   Health    0.705284
45          farewell contribution     Gift    0.722347
3           farewell contribution     Gift    0.722347
126         farewell contribution     Gift    0.722347
160         farewell contribution     Gift    0.722347
197         farewell contribution     Gift    0.722347
194         farewell contribution     Gift    0.722347
180         farewell contribution     Gift    0.722347
92          farewell contribution     Gift    0.722347
95          farewell contribution     Gift    0.722347
223                  laptop table    Other    0.745326
40                Sugaran Kitchen     Food    0.772318
99                Sugaran Kitchen     Food    0.772318
101               Sugaran Kitchen     Food    0.772318
87                  At restaurant     Food    0.783252

======================================================================
ERRORS BY ACTUAL CATEGORY
======================================================================
actual
Other             8
Household         8
Health            7
Family            4
Food              4
Leisure           3
Apparel           2
Transportation    1
Gift              1
Subscription      1
Name: count, dtype: int64

======================================================================
ERRORS BY PREDICTED CATEGORY
======================================================================
predicted
Household         12
Other             10
Food               6
Transportation     4
Health             2
Subscription       1
Beauty             1
Family             1
Apparel            1
Gift               1
Name: count, dtype: int64

In [20]:
# ============================================================
# STEP 19 — INSPECT WEAK CATEGORY TRAINING EXAMPLES
# ============================================================

weak_categories = [
    "Family",
    "Leisure",
    "Other",
    "Household",
    "Health"
]


for category in weak_categories:

    print("\n")
    print("=" * 75)
    print("CATEGORY:", category)
    print("=" * 75)

    # --------------------------------------------------------
    # Get unique training examples
    # --------------------------------------------------------

    examples = (
        train_df[
            train_df["category"] == category
        ][
            ["text", "category"]
        ]
        .drop_duplicates()
        .sort_values("text")
    )


    print(
        "Unique training texts:",
        len(examples)
    )

    print(
        "\nTraining examples:"
    )

    display(
        examples[
            ["text", "category"]
        ].reset_index(
            drop=True
        )
    )

===========================================================================
CATEGORY: Family
===========================================================================
Unique training texts: 17

Training examples:

                  text category
0           Belt + bow   Family
1            Body mist   Family
2                 Bows   Family
3            Fab India   Family
4     Family exam form   Family
5         For utensils   Family
6          H&M clothes   Family
7     Himalaya shampoo   Family
8       PET Psychology   Family
9              Trouser   Family
10        baggit purse   Family
11          ipad cover   Family
12            leggings   Family
13  scratch guard ipad   Family
14             sweater   Family
15               syrup   Family
16               tonic   Family

===========================================================================
CATEGORY: Leisure
===========================================================================
Unique training texts: 10

Training examples:

                           text category
0                      monument  Leisure
1                             2  Leisure
2              2 Batman tickets  Leisure
3                        2 PVR   Leisure
4                 2 PVR Place 6  Leisure
5  2 tickets - Cinepolis 4DX 3D  Leisure
6              Finding next Job  Leisure
7                       Imax 3D  Leisure
8                  Misc expense  Leisure
9                   Planetarium  Leisure

===========================================================================
CATEGORY: Other
===========================================================================
Unique training texts: 73

Training examples:

                                            text category
0                                      2 kg soil    Other
1                                     ATM charge    Other
2                          Aadhar Address Change    Other
3                       Aadhar PUC card delivery    Other
4                                   Amazon prime    Other
..                                           ...      ...
68                          splitwise settlement    Other
69  stationary (drawing book + black sketch pen)    Other
70                                  watch repair    Other
71                                  wedding gift    Other
72                                         xerox    Other

[73 rows x 2 columns]

===========================================================================
CATEGORY: Household
===========================================================================
Unique training texts: 99

Training examples:

                               text   category
0           2 Bedsheets (1500 each)  Household
1                     2 Spike guard  Household
2                  2 locks for bags  Household
3   2 toast+ 2 parle g + Marie gold  Household
4                 3 Wall clock cell  Household
..                              ...        ...
94                          plumber  Household
95                        refilling  Household
96             sensitive toothbrush  Household
97             sensodyne rapid fire  Household
98             sensodyne toothbrush  Household

[99 rows x 2 columns]

===========================================================================
CATEGORY: Health
===========================================================================
Unique training texts: 56

Training examples:

                                                 text category
0                                    2 All out refill   Health
1   2 Thyroid (1000) + cholesterol (220) + uric ac...   Health
2                                         2 n95 masks   Health
3                                          3 Sinarest   Health
4                                     3 tablet Nor tz   Health
5                               4 paracetamol tablets   Health
6                                       5 Meftal spas   Health
7                                     Acne Star cream   Health
8                                      All out refill   Health
9                                 Boroline + band aid   Health
10                              Candid dusting powder   Health
11                                           Cinarest   Health
12                                  Cough-sills 4 pcs   Health
13                 Cough-sills 4 pcs + sinarest 3 pcs   Health
14                               Covaxin booster dose   Health
15                                Family Thyroid Test   Health
16                          Family Thyroid Test + CBC   Health
17                                   Family's Glasses   Health
18                                    Glasses advance   Health
19                                  Glasses remaining   Health
20          Glucose D(50) + flora bc (40)+cyra 20(10)   Health
21                              Hospital consultation   Health
22                                                Jel   Health
23                                            Limcee+   Health
24                                           Move jel   Health
25                                        Q-dee strip   Health
26                                 Refresh Tears Drop   Health
27           Routine checkup - eye institute, Place 6   Health
28                                 Sofy antibacterial   Health
29                                        Suppliemnts   Health
30                               Surgical gloves pair   Health
31                                             Tablet   Health
32                                    Thyroid Tablets   Health
33                                             V-wash   Health
34                                      Vicks VapoRub   Health
35                         adulsa ( tonic for cough )   Health
36                                 citrizen + crocine   Health
37                                   dentist check-up   Health
38                                           eye drop   Health
39                                  eye drop maxmoist   Health
40                            eyewear Glasses advance   Health
41                  eyewear Glasses payment remaining   Health
42                                          face mask   Health
43                                     hand sanitizer   Health
44                   hand sanitizer + surgical gloves   Health
45                                           kala hit   Health
46                                             koflet   Health
47                                        meftal spas   Health
48                                        mouth fresh   Health
49                                        painkillers   Health
50                                 root canal advance   Health
51                                     root canal due   Health
52                                          strepsils   Health
53                                  strepsils 1 strip   Health
54                                 strepsils 13 pills   Health
55                       syrup+tablet+ mortein refill   Health

In [21]:
# ============================================================
# STEP 20 — CREATE TEMPERED CLASS WEIGHTS
# ============================================================

import numpy as np
import torch


# ============================================================
# 1. ORIGINAL BALANCED WEIGHTS
# ============================================================

original_weights = class_weights.copy()


# ============================================================
# 2. TEMPER THE WEIGHTS
# ============================================================

tempered_weights = np.sqrt(
    original_weights
)


# ============================================================
# 3. NORMALIZE WEIGHTS
# ============================================================

# Make the average weight approximately 1.
tempered_weights = (
    tempered_weights
    / tempered_weights.mean()
)


# ============================================================
# 4. MOVE TO GPU
# ============================================================

tempered_category_weights = torch.tensor(
    tempered_weights,
    dtype=torch.float32
).to(device)


# ============================================================
# 5. COMPARE OLD VS NEW
# ============================================================

print("=" * 70)
print("ORIGINAL VS TEMPERED CLASS WEIGHTS")
print("=" * 70)

for category_id, category_name in enumerate(
    category_labels
):

    print(
        f"{category_id:2d} | "
        f"{category_name:15s} | "
        f"Original = {original_weights[category_id]:.4f} | "
        f"Tempered = {tempered_weights[category_id]:.4f}"
    )


# ============================================================
# 6. STATISTICS
# ============================================================

print("\n" + "=" * 70)
print("WEIGHT STATISTICS")
print("=" * 70)

print(
    "Original minimum:",
    round(
        original_weights.min(),
        4
    )
)

print(
    "Original maximum:",
    round(
        original_weights.max(),
        4
    )
)

print(
    "Tempered minimum:",
    round(
        tempered_weights.min(),
        4
    )
)

print(
    "Tempered maximum:",
    round(
        tempered_weights.max(),
        4
    )
)

print(
    "Tempered mean:",
    round(
        tempered_weights.mean(),
        4
    )
)

======================================================================
ORIGINAL VS TEMPERED CLASS WEIGHTS
======================================================================
 0 | Apparel         | Original = 2.8088 | Tempered = 0.9893
 1 | Beauty          | Original = 5.3367 | Tempered = 1.3636
 2 | Education       | Original = 7.6238 | Tempered = 1.6299
 3 | Family          | Original = 5.9296 | Tempered = 1.4374
 4 | Festivals       | Original = 7.6238 | Tempered = 1.6299
 5 | Food            | Original = 0.1470 | Tempered = 0.2263
 6 | Gift            | Original = 5.6175 | Tempered = 1.3991
 7 | Health          | Original = 1.5033 | Tempered = 0.7237
 8 | Household       | Original = 0.7906 | Tempered = 0.5249
 9 | Investment      | Original = 1.3684 | Tempered = 0.6905
10 | Leisure         | Original = 8.2103 | Tempered = 1.6914
11 | Other           | Original = 1.0891 | Tempered = 0.6160
12 | Salary          | Original = 2.4822 | Tempered = 0.9300
13 | Subscription    | Original = 1.6677 | Tempered = 0.7623
14 | Transportation  | Original = 0.4269 | Tempered = 0.3857

======================================================================
WEIGHT STATISTICS
======================================================================
Original minimum: 0.147
Original maximum: 8.2103
Tempered minimum: 0.2263
Tempered maximum: 1.6914
Tempered mean: 1.0

In [22]:
# ============================================================
# STEP 21 — FRESH MuRIL + TEMPERED CLASS WEIGHTS
# ============================================================

import torch
import torch.nn as nn
from transformers import AutoModel


# ============================================================
# 1. LOAD A FRESH MuRIL BACKBONE
# ============================================================

MODEL_NAME = "google/muril-base-cased"

print("Loading fresh MuRIL model...")

fresh_bert = AutoModel.from_pretrained(
    MODEL_NAME
)

print("Fresh MuRIL loaded!")


# ============================================================
# 2. BUILD A FRESH CLASSIFIER
# ============================================================

tempered_model = TransactionClassifier(
    bert_model=fresh_bert,
    num_types=len(type_labels),
    num_categories=len(category_labels)
)


# ============================================================
# 3. MOVE MODEL TO GPU
# ============================================================

tempered_model = tempered_model.to(
    device
)


# ============================================================
# 4. CREATE LOSS FUNCTIONS
# ============================================================

tempered_type_loss_fn = nn.CrossEntropyLoss()

tempered_category_loss_fn = nn.CrossEntropyLoss(
    weight=tempered_category_weights
)


# ============================================================
# 5. CREATE FRESH OPTIMIZER
# ============================================================

tempered_optimizer = torch.optim.AdamW(
    tempered_model.parameters(),
    lr=2e-5
)


# ============================================================
# 6. MODEL INFORMATION
# ============================================================

print("\n" + "=" * 70)
print("TEMPERED-WEIGHT EXPERIMENT")
print("=" * 70)

print(
    "Device:",
    device
)

print(
    "Categories:",
    len(category_labels)
)

print(
    "Types:",
    len(type_labels)
)

print(
    "Learning rate:",
    2e-5
)

print(
    "Category loss:",
    "Tempered Weighted CrossEntropyLoss"
)


# ============================================================
# 7. COUNT PARAMETERS
# ============================================================

tempered_total_params = sum(
    p.numel()
    for p in tempered_model.parameters()
)

tempered_trainable_params = sum(
    p.numel()
    for p in tempered_model.parameters()
    if p.requires_grad
)

print(
    "\nTotal parameters:",
    f"{tempered_total_params:,}"
)

print(
    "Trainable parameters:",
    f"{tempered_trainable_params:,}"
)


# ============================================================
# 8. TEST ONE BATCH
# ============================================================

tempered_model.train()

batch = next(
    iter(train_loader)
)

input_ids = batch[
    "input_ids"
].to(
    device,
    non_blocking=True
)

attention_mask = batch[
    "attention_mask"
].to(
    device,
    non_blocking=True
)

type_ids = batch[
    "type_label"
].to(
    device,
    non_blocking=True
)

category_ids = batch[
    "category_label"
].to(
    device,
    non_blocking=True
)


# Forward pass
type_logits, category_logits = tempered_model(
    input_ids,
    attention_mask
)


# Losses
type_loss = tempered_type_loss_fn(
    type_logits,
    type_ids
)

category_loss = tempered_category_loss_fn(
    category_logits,
    category_ids
)

total_loss = (
    type_loss
    + category_loss
)


# ============================================================
# 9. DISPLAY TEST
# ============================================================

print("\n" + "=" * 70)
print("ONE-BATCH TEST")
print("=" * 70)

print(
    "Input shape:",
    input_ids.shape
)

print(
    "Type logits:",
    type_logits.shape
)

print(
    "Category logits:",
    category_logits.shape
)

print(
    "Type loss:",
    round(
        type_loss.item(),
        4
    )
)

print(
    "Category loss:",
    round(
        category_loss.item(),
        4
    )
)

print(
    "Total loss:",
    round(
        total_loss.item(),
        4
    )
)

Loading fresh MuRIL model...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: google/muril-base-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
bert.embeddings.position_ids               | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Fresh MuRIL loaded!

======================================================================
TEMPERED-WEIGHT EXPERIMENT
======================================================================
Device: cuda
Categories: 15
Types: 2
Learning rate: 2e-05
Category loss: Tempered Weighted CrossEntropyLoss

Total parameters: 237,569,297
Trainable parameters: 237,569,297

======================================================================
ONE-BATCH TEST
======================================================================
Input shape: torch.Size([16, 32])
Type logits: torch.Size([16, 2])
Category logits: torch.Size([16, 15])
Type loss: 0.7076
Category loss: 2.7134
Total loss: 3.421

In [23]:
# ============================================================
# STEP 21 — CREATE WHATSAPP / HINGLISH DATASET
# ============================================================

import pandas as pd


# ============================================================
# 1. WHATSAPP MESSAGE TEMPLATES
# ============================================================

expense_templates = [
    "yaar {text} pe paise lag gaye",
    "bhai {text} ka kharcha hua",
    "aaj {text} ke liye payment kiya",
    "maine {text} liya, paise chale gaye",
    "aaj {text} ke paise diye",
    "just {text} ka payment kar diya",
    "{text} le liya yaar",
    "bhai aaj {text} par spend kiya",
    "{text} ka paisa de diya",
    "aaj {text} ke liye pay kiya"
]

income_templates = [
    "yaar {text} aa gayi",
    "bhai {text} mil gayi",
    "aaj {text} receive hui",
    "account me {text} aayi",
    "{text} credited ho gayi",
    "aaj mujhe {text} mila",
    "{text} aa gaya account me",
    "bhai aaj {text} receive hua"
]


# ============================================================
# 2. FUNCTION TO GENERATE WHATSAPP VARIANTS
# ============================================================

def generate_whatsapp_variants(
    dataframe,
    variants_per_text=8
):

    rows = []

    # Use unique text + category + type
    unique_data = (
        dataframe[
            [
                "text",
                "category",
                "type",
                "category_id",
                "type_id"
            ]
        ]
        .drop_duplicates()
        .reset_index(drop=True)
    )

    for _, row in unique_data.iterrows():

        original_text = str(
            row["text"]
        )

        category = row["category"]
        transaction_type = row["type"]

        category_id = row["category_id"]
        type_id = row["type_id"]

        # ----------------------------------------------------
        # Choose templates based on income/expense
        # ----------------------------------------------------

        if transaction_type == "Income":
            templates = income_templates
        else:
            templates = expense_templates

        # ----------------------------------------------------
        # Keep only requested number
        # ----------------------------------------------------

        selected_templates = templates[
            :variants_per_text
        ]

        # ----------------------------------------------------
        # Add original text
        # ----------------------------------------------------

        rows.append({
            "text": original_text,
            "category": category,
            "type": transaction_type,
            "category_id": category_id,
            "type_id": type_id,
            "style": "original"
        })

        # ----------------------------------------------------
        # Add WhatsApp variants
        # ----------------------------------------------------

        for template in selected_templates:

            whatsapp_text = template.format(
                text=original_text
            )

            rows.append({
                "text": whatsapp_text,
                "category": category,
                "type": transaction_type,
                "category_id": category_id,
                "type_id": type_id,
                "style": "whatsapp"
            })

    return pd.DataFrame(rows)


# ============================================================
# 3. GENERATE TRAINING DATA
# ============================================================

whatsapp_train_df = generate_whatsapp_variants(
    train_df,
    variants_per_text=8
)


# ============================================================
# 4. GENERATE VALIDATION DATA
# ============================================================

whatsapp_val_df = generate_whatsapp_variants(
    val_df,
    variants_per_text=8
)


# ============================================================
# 5. DISPLAY DATASET SIZES
# ============================================================

print("=" * 70)
print("WHATSAPP DATASET SIZES")
print("=" * 70)

print(
    "Original training rows:",
    len(train_df)
)

print(
    "WhatsApp training rows:",
    len(whatsapp_train_df)
)

print(
    "Original validation rows:",
    len(val_df)
)

print(
    "WhatsApp validation rows:",
    len(whatsapp_val_df)
)


# ============================================================
# 6. CHECK CATEGORY DISTRIBUTION
# ============================================================

print("\n" + "=" * 70)
print("WHATSAPP TRAIN CATEGORY DISTRIBUTION")
print("=" * 70)

print(
    whatsapp_train_df[
        "category"
    ].value_counts()
)


print("\n" + "=" * 70)
print("WHATSAPP VALIDATION CATEGORY DISTRIBUTION")
print("=" * 70)

print(
    whatsapp_val_df[
        "category"
    ].value_counts()
)


# ============================================================
# 7. SHOW ACTUAL WHATSAPP EXAMPLES
# ============================================================

print("\n" + "=" * 70)
print("WHATSAPP-STYLE EXAMPLES")
print("=" * 70)

display(
    whatsapp_train_df[
        whatsapp_train_df["style"] == "whatsapp"
    ][
        [
            "text",
            "category"
        ]
    ].head(40)
)


# ============================================================
# 8. CHECK FOR CROSS-SPLIT TEXT LEAKAGE
# ============================================================

train_texts = set(
    whatsapp_train_df["text"]
)

val_texts = set(
    whatsapp_val_df["text"]
)

overlap = train_texts.intersection(
    val_texts
)

print("\n" + "=" * 70)
print("CROSS-SPLIT LEAKAGE CHECK")
print("=" * 70)

print(
    "Exact texts appearing in both:",
    len(overlap)
)


# ============================================================
# 9. SHOW SOME REALISTIC EXAMPLES FROM DIFFERENT CLASSES
# ============================================================

print("\n" + "=" * 70)
print("SAMPLE BY CATEGORY")
print("=" * 70)

for category in [
    "Food",
    "Apparel",
    "Health",
    "Transportation",
    "Subscription",
    "Family",
    "Leisure"
]:

    sample = whatsapp_train_df[
        (
            whatsapp_train_df["category"]
            == category
        )
        &
        (
            whatsapp_train_df["style"]
            == "whatsapp"
        )
    ].head(3)

    print("\nCATEGORY:", category)

    for text in sample["text"]:
        print("-", text)

======================================================================
WHATSAPP DATASET SIZES
======================================================================
Original training rows: 1601
WhatsApp training rows: 7911
Original validation rows: 254
WhatsApp validation rows: 1404

======================================================================
WHATSAPP TRAIN CATEGORY DISTRIBUTION
======================================================================
category
Food              3159
Transportation    1413
Household          891
Other              657
Health             504
Apparel            252
Investment         207
Subscription       189
Family             153
Gift               126
Education          108
Leisure             90
Festivals           81
Beauty              72
Salary               9
Name: count, dtype: int64

======================================================================
WHATSAPP VALIDATION CATEGORY DISTRIBUTION
======================================================================
category
Food              558
Transportation    252
Household         162
Other             117
Health             90
Apparel            45
Investment         36
Subscription       36
Family             27
Gift               18
Beauty             18
Leisure            18
Education          18
Festivals           9
Name: count, dtype: int64

======================================================================
WHATSAPP-STYLE EXAMPLES
======================================================================

                                                 text      category
1   yaar Idli medu Vada mix 2 plates pe paise lag ...          Food
2     bhai Idli medu Vada mix 2 plates ka kharcha hua          Food
3   aaj Idli medu Vada mix 2 plates ke liye paymen...          Food
4   maine Idli medu Vada mix 2 plates liya, paise ...          Food
5       aaj Idli medu Vada mix 2 plates ke paise diye          Food
6   just Idli medu Vada mix 2 plates ka payment ka...          Food
7            Idli medu Vada mix 2 plates le liya yaar          Food
8   bhai aaj Idli medu Vada mix 2 plates par spend...          Food
10        yaar 1 month subscription pe paise lag gaye  Subscription
11           bhai 1 month subscription ka kharcha hua  Subscription
12      aaj 1 month subscription ke liye payment kiya  Subscription
13  maine 1 month subscription liya, paise chale gaye  Subscription
14             aaj 1 month subscription ke paise diye  Subscription
15      just 1 month subscription ka payment kar diya  Subscription
16                  1 month subscription le liya yaar  Subscription
17       bhai aaj 1 month subscription par spend kiya  Subscription
19           yaar Data booster pack pe paise lag gaye  Subscription
20              bhai Data booster pack ka kharcha hua  Subscription
21         aaj Data booster pack ke liye payment kiya  Subscription
22     maine Data booster pack liya, paise chale gaye  Subscription
23                aaj Data booster pack ke paise diye  Subscription
24         just Data booster pack ka payment kar diya  Subscription
25                     Data booster pack le liya yaar  Subscription
26          bhai aaj Data booster pack par spend kiya  Subscription
28                 yaar Ganesh idol pe paise lag gaye     Festivals
29                    bhai Ganesh idol ka kharcha hua     Festivals
30               aaj Ganesh idol ke liye payment kiya     Festivals
31           maine Ganesh idol liya, paise chale gaye     Festivals
32                      aaj Ganesh idol ke paise diye     Festivals
33               just Ganesh idol ka payment kar diya     Festivals
34                           Ganesh idol le liya yaar     Festivals
35                bhai aaj Ganesh idol par spend kiya     Festivals
37  yaar Permanent Residence - Tata Play recharge ...  Subscription
38  bhai Permanent Residence - Tata Play recharge ...  Subscription
39  aaj Permanent Residence - Tata Play recharge k...  Subscription
40  maine Permanent Residence - Tata Play recharge...  Subscription
41  aaj Permanent Residence - Tata Play recharge k...  Subscription
42  just Permanent Residence - Tata Play recharge ...  Subscription
43  Permanent Residence - Tata Play recharge le li...  Subscription
44  bhai aaj Permanent Residence - Tata Play recha...  Subscription

======================================================================
CROSS-SPLIT LEAKAGE CHECK
======================================================================
Exact texts appearing in both: 0

======================================================================
SAMPLE BY CATEGORY
======================================================================

CATEGORY: Food
- yaar Idli medu Vada mix 2 plates pe paise lag gaye
- bhai Idli medu Vada mix 2 plates ka kharcha hua
- aaj Idli medu Vada mix 2 plates ke liye payment kiya

CATEGORY: Apparel
- yaar 11 clothes ironing pe paise lag gaye
- bhai 11 clothes ironing ka kharcha hua
- aaj 11 clothes ironing ke liye payment kiya

CATEGORY: Health
- yaar eyewear Glasses payment remaining pe paise lag gaye
- bhai eyewear Glasses payment remaining ka kharcha hua
- aaj eyewear Glasses payment remaining ke liye payment kiya

CATEGORY: Transportation
- yaar Place 2 station to Permanent Residence pe paise lag gaye
- bhai Place 2 station to Permanent Residence ka kharcha hua
- aaj Place 2 station to Permanent Residence ke liye payment kiya

CATEGORY: Subscription
- yaar 1 month subscription pe paise lag gaye
- bhai 1 month subscription ka kharcha hua
- aaj 1 month subscription ke liye payment kiya

CATEGORY: Family
- yaar Bows pe paise lag gaye
- bhai Bows ka kharcha hua
- aaj Bows ke liye payment kiya

CATEGORY: Leisure
- yaar 2 PVR  pe paise lag gaye
- bhai 2 PVR  ka kharcha hua
- aaj 2 PVR  ke liye payment kiya

In [24]:
# ============================================================
# STEP 22 — CREATE REALISTIC WHATSAPP TEST SET
# ============================================================

real_whatsapp_test = [

    # ---------------- FOOD ----------------
    ("yaar 250 ka pizza mangaya", "Food"),
    ("aaj 180 ka burger khaya", "Food"),
    ("swiggy pe 420 ka dinner order kiya", "Food"),
    ("bhai chai aur snacks pe 90 rupaye gaye", "Food"),
    ("250 ka paneer order kar diya", "Food"),

    # ---------------- APPAREL ----------------
    ("amazon se 1800 ke shoes liye", "Apparel"),
    ("bhai 1200 ki tshirt kharidi", "Apparel"),
    ("aaj 900 ka kurta liya", "Apparel"),
    ("1500 ki jeans le li", "Apparel"),

    # ---------------- HEALTH ----------------
    ("doctor ko 600 diye", "Health"),
    ("medicine pe 350 kharch hue", "Health"),
    ("bhai 1200 ki medicines li", "Health"),
    ("eye checkup ka 800 laga", "Health"),

    # ---------------- TRANSPORTATION ----------------
    ("uber se ghar aaya 220", "Transportation"),
    ("aaj auto ke 120 diye", "Transportation"),
    ("metro ka 60 ka ticket liya", "Transportation"),
    ("cab pe 450 kharch hue", "Transportation"),

    # ---------------- SUBSCRIPTION ----------------
    ("netflix ka 199 wala plan renew kiya", "Subscription"),
    ("spotify ke 119 rupaye diye", "Subscription"),
    ("bhai mobile recharge 299 ka kiya", "Subscription"),
    ("tata play recharge 350 ka hua", "Subscription"),

    # ---------------- HOUSEHOLD ----------------
    ("ghar ke liye 1200 ka bedsheet liya", "Household"),
    ("500 ke cleaning supplies liye", "Household"),
    ("bhai 300 ka bulb aur switch liya", "Household"),
    ("ghar ke saman pe 900 lage", "Household"),

    # ---------------- INVESTMENT ----------------
    ("bhai 5000 mutual fund me daale", "Investment"),
    ("aaj 2000 ka sip kiya", "Investment"),
    ("zerodha me 3000 invest kiye", "Investment"),

    # ---------------- GIFT ----------------
    ("friend ke birthday pe 700 ka gift liya", "Gift"),
    ("bhai shaadi ke gift pe 1500 lage", "Gift"),

    # ---------------- EDUCATION ----------------
    ("course ke 2000 diye", "Education"),
    ("college form ke 500 lage", "Education"),

    # ---------------- LEISURE ----------------
    ("aaj movie ke 500 lage", "Leisure"),
    ("pvr me 700 kharch hue", "Leisure"),
    ("weekend outing pe 1000 gaye", "Leisure"),

    # ---------------- BEAUTY ----------------
    ("haircut ke 300 diye", "Beauty"),
    ("salon pe 800 kharch hue", "Beauty"),

    # ---------------- FAMILY ----------------
    ("mummy ke liye 1500 ka saman liya", "Family"),
    ("bhai ko 500 ka gift diya", "Family"),

    # ---------------- FESTIVALS ----------------
    ("diwali ke saman pe 1200 kharch hue", "Festivals"),
    ("puja ka saman 600 ka liya", "Festivals"),

    # ---------------- OTHER ----------------
    ("yaar 250 ka random expense ho gaya", "Other"),
    ("500 ka miscellaneous kharcha ho gaya", "Other"),

    # ---------------- SALARY ----------------
    ("aaj salary 45000 aa gayi", "Salary"),
    ("bhai salary credit ho gayi 50000", "Salary"),
]


# ============================================================
# CREATE DATAFRAME
# ============================================================

real_whatsapp_test_df = pd.DataFrame(
    real_whatsapp_test,
    columns=[
        "text",
        "category"
    ]
)


# ============================================================
# MAP CATEGORY TO ID
# ============================================================

real_whatsapp_test_df["category_id"] = (
    real_whatsapp_test_df["category"]
    .map(category_to_id)
)


# ============================================================
# CHECK RESULTS
# ============================================================

print("=" * 70)
print("REALISTIC WHATSAPP TEST SET")
print("=" * 70)

print(
    "Number of test messages:",
    len(real_whatsapp_test_df)
)

print(
    "\nCategory distribution:"
)

print(
    real_whatsapp_test_df[
        "category"
    ].value_counts()
)


print(
    "\nMissing category IDs:",
    real_whatsapp_test_df[
        "category_id"
    ].isna().sum()
)


print(
    "\nSample messages:"
)

display(
    real_whatsapp_test_df.head(20)
)

======================================================================
REALISTIC WHATSAPP TEST SET
======================================================================
Number of test messages: 45

Category distribution:
category
Food              5
Apparel           4
Health            4
Transportation    4
Subscription      4
Household         4
Investment        3
Leisure           3
Gift              2
Education         2
Beauty            2
Family            2
Festivals         2
Other             2
Salary            2
Name: count, dtype: int64

Missing category IDs: 0

Sample messages:

                                      text        category  category_id
0                yaar 250 ka pizza mangaya            Food            5
1                  aaj 180 ka burger khaya            Food            5
2       swiggy pe 420 ka dinner order kiya            Food            5
3   bhai chai aur snacks pe 90 rupaye gaye            Food            5
4             250 ka paneer order kar diya            Food            5
5             amazon se 1800 ke shoes liye         Apparel            0
6              bhai 1200 ki tshirt kharidi         Apparel            0
7                    aaj 900 ka kurta liya         Apparel            0
8                      1500 ki jeans le li         Apparel            0
9                       doctor ko 600 diye          Health            7
10              medicine pe 350 kharch hue          Health            7
11               bhai 1200 ki medicines li          Health            7
12                 eye checkup ka 800 laga          Health            7
13                   uber se ghar aaya 220  Transportation           14
14                    aaj auto ke 120 diye  Transportation           14
15              metro ka 60 ka ticket liya  Transportation           14
16                   cab pe 450 kharch hue  Transportation           14
17     netflix ka 199 wala plan renew kiya    Subscription           13
18              spotify ke 119 rupaye diye    Subscription           13
19        bhai mobile recharge 299 ka kiya    Subscription           13

In [25]:
# ============================================================
# STEP 23 — BUILD WHATSAPP TRAINING / VALIDATION LOADERS
# ============================================================

import torch
from torch.utils.data import Dataset, DataLoader


# ============================================================
# 1. SETTINGS
# ============================================================

WHATSAPP_MAX_LENGTH = 32
WHATSAPP_BATCH_SIZE = 16


# ============================================================
# 2. DATASET CLASS
# ============================================================

class WhatsAppTransactionDataset(Dataset):

    def __init__(
        self,
        dataframe,
        tokenizer,
        max_length=32
    ):

        self.data = dataframe.reset_index(
            drop=True
        )

        self.tokenizer = tokenizer
        self.max_length = max_length


    def __len__(self):

        return len(self.data)


    def __getitem__(self, idx):

        text = str(
            self.data.loc[idx, "text"]
        )

        encoding = self.tokenizer(
            text,
            truncation=True,
            padding="max_length",
            max_length=self.max_length,
            return_tensors="pt"
        )

        return {
            "input_ids": encoding[
                "input_ids"
            ].squeeze(0),

            "attention_mask": encoding[
                "attention_mask"
            ].squeeze(0),

            "type_label": torch.tensor(
                self.data.loc[idx, "type_id"],
                dtype=torch.long
            ),

            "category_label": torch.tensor(
                self.data.loc[idx, "category_id"],
                dtype=torch.long
            )
        }


# ============================================================
# 3. CREATE DATASETS
# ============================================================

whatsapp_train_dataset = WhatsAppTransactionDataset(
    whatsapp_train_df,
    tokenizer,
    WHATSAPP_MAX_LENGTH
)

whatsapp_val_dataset = WhatsAppTransactionDataset(
    whatsapp_val_df,
    tokenizer,
    WHATSAPP_MAX_LENGTH
)


# ============================================================
# 4. CREATE DATALOADERS
# ============================================================

whatsapp_train_loader = DataLoader(
    whatsapp_train_dataset,
    batch_size=WHATSAPP_BATCH_SIZE,
    shuffle=True,
    num_workers=2,
    pin_memory=torch.cuda.is_available()
)

whatsapp_val_loader = DataLoader(
    whatsapp_val_dataset,
    batch_size=WHATSAPP_BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=torch.cuda.is_available()
)


# ============================================================
# 5. DISPLAY INFORMATION
# ============================================================

print("=" * 70)
print("WHATSAPP DATALOADERS")
print("=" * 70)

print(
    "Training dataset:",
    len(whatsapp_train_dataset)
)

print(
    "Validation dataset:",
    len(whatsapp_val_dataset)
)

print(
    "Batch size:",
    WHATSAPP_BATCH_SIZE
)

print(
    "Training batches:",
    len(whatsapp_train_loader)
)

print(
    "Validation batches:",
    len(whatsapp_val_loader)
)


# ============================================================
# 6. CHECK ONE BATCH
# ============================================================

batch = next(
    iter(whatsapp_train_loader)
)

print("\n" + "=" * 70)
print("ONE WHATSAPP BATCH")
print("=" * 70)

print(
    "input_ids:",
    batch["input_ids"].shape
)

print(
    "attention_mask:",
    batch["attention_mask"].shape
)

print(
    "type_label:",
    batch["type_label"].shape
)

print(
    "category_label:",
    batch["category_label"].shape
)

======================================================================
WHATSAPP DATALOADERS
======================================================================
Training dataset: 7911
Validation dataset: 1404
Batch size: 16
Training batches: 495
Validation batches: 88

======================================================================
ONE WHATSAPP BATCH
======================================================================
input_ids: torch.Size([16, 32])
attention_mask: torch.Size([16, 32])
type_label: torch.Size([16])
category_label: torch.Size([16])

In [26]:
# ============================================================
# STEP 24 — LOAD BEST MODEL FOR WHATSAPP FINE-TUNING
# ============================================================

import torch
import torch.nn as nn


# ============================================================
# 1. LOAD THE ORIGINAL BEST CHECKPOINT
# ============================================================

BEST_MODEL_PATH = (
    "/kaggle/working/"
    "muril_original_best.pt"
)

print("Loading original best MuRIL checkpoint...")


model.load_state_dict(
    torch.load(
        BEST_MODEL_PATH,
        map_location=device
    )
)

model = model.to(device)

print("Checkpoint loaded successfully!")


# ============================================================
# 2. CREATE WHATSAPP-TUNING LOSS FUNCTIONS
# ============================================================

whatsapp_type_loss_fn = nn.CrossEntropyLoss()

whatsapp_category_loss_fn = nn.CrossEntropyLoss(
    weight=category_class_weights
)


# ============================================================
# 3. CREATE A SMALLER LEARNING RATE
# ============================================================

whatsapp_optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=1e-5,
    weight_decay=0.01
)


# ============================================================
# 4. CHECK MODEL PARAMETER COUNT
# ============================================================

trainable_params = sum(
    p.numel()
    for p in model.parameters()
    if p.requires_grad
)


print("\n" + "=" * 70)
print("WHATSAPP FINE-TUNING CONFIGURATION")
print("=" * 70)

print(
    "Trainable parameters:",
    f"{trainable_params:,}"
)

print(
    "Learning rate:",
    1e-5
)

print(
    "Weight decay:",
    0.01
)

print(
    "Category loss:",
    "Weighted CrossEntropyLoss"
)


# ============================================================
# 5. TEST ONE WHATSAPP BATCH
# ============================================================

model.eval()

batch = next(
    iter(whatsapp_train_loader)
)

input_ids = batch[
    "input_ids"
].to(
    device,
    non_blocking=True
)

attention_mask = batch[
    "attention_mask"
].to(
    device,
    non_blocking=True
)

type_ids = batch[
    "type_label"
].to(
    device,
    non_blocking=True
)

category_ids = batch[
    "category_label"
].to(
    device,
    non_blocking=True
)


with torch.no_grad():

    type_logits, category_logits = model(
        input_ids,
        attention_mask
    )


# ============================================================
# 6. CALCULATE TEST LOSSES
# ============================================================

type_loss = whatsapp_type_loss_fn(
    type_logits,
    type_ids
)

category_loss = whatsapp_category_loss_fn(
    category_logits,
    category_ids
)

total_loss = (
    type_loss
    + category_loss
)


# ============================================================
# 7. DISPLAY RESULTS
# ============================================================

print("\n" + "=" * 70)
print("WHATSAPP ONE-BATCH TEST")
print("=" * 70)

print(
    "Input shape:",
    input_ids.shape
)

print(
    "Type logits:",
    type_logits.shape
)

print(
    "Category logits:",
    category_logits.shape
)

print(
    "Type loss:",
    round(
        type_loss.item(),
        4
    )
)

print(
    "Category loss:",
    round(
        category_loss.item(),
        4
    )
)

print(
    "Total loss:",
    round(
        total_loss.item(),
        4
    )
)

Loading original best MuRIL checkpoint...
Checkpoint loaded successfully!

======================================================================
WHATSAPP FINE-TUNING CONFIGURATION
======================================================================
Trainable parameters: 237,569,297
Learning rate: 1e-05
Weight decay: 0.01
Category loss: Weighted CrossEntropyLoss

======================================================================
WHATSAPP ONE-BATCH TEST
======================================================================
Input shape: torch.Size([16, 32])
Type logits: torch.Size([16, 2])
Category logits: torch.Size([16, 15])
Type loss: 0.0015
Category loss: 0.221
Total loss: 0.2225

In [27]:
# ============================================================
# STEP 25 — WHATSAPP FINE-TUNING
# ============================================================

import torch
import numpy as np

from sklearn.metrics import (
    accuracy_score,
    f1_score
)


# ============================================================
# 1. CONFIGURATION
# ============================================================

NUM_EPOCHS = 6

BEST_WHATSAPP_MODEL_PATH = (
    "/kaggle/working/"
    "muril_whatsapp_best.pt"
)

best_val_macro_f1 = -1.0
best_val_accuracy = -1.0
patience = 2
epochs_without_improvement = 0


# ============================================================
# 2. EVALUATION FUNCTION
# ============================================================

def evaluate_whatsapp(loader):

    model.eval()

    all_type_true = []
    all_type_pred = []

    all_category_true = []
    all_category_pred = []

    total_loss = 0.0

    with torch.no_grad():

        for batch in loader:

            input_ids = batch[
                "input_ids"
            ].to(
                device,
                non_blocking=True
            )

            attention_mask = batch[
                "attention_mask"
            ].to(
                device,
                non_blocking=True
            )

            type_ids = batch[
                "type_label"
            ].to(
                device,
                non_blocking=True
            )

            category_ids = batch[
                "category_label"
            ].to(
                device,
                non_blocking=True
            )

            # Forward pass
            type_logits, category_logits = model(
                input_ids,
                attention_mask
            )

            # Loss
            type_loss = whatsapp_type_loss_fn(
                type_logits,
                type_ids
            )

            category_loss = whatsapp_category_loss_fn(
                category_logits,
                category_ids
            )

            loss = type_loss + category_loss

            total_loss += loss.item()

            # Predictions
            type_preds = torch.argmax(
                type_logits,
                dim=1
            )

            category_preds = torch.argmax(
                category_logits,
                dim=1
            )

            # Move to CPU
            all_type_true.extend(
                type_ids.cpu().numpy()
            )

            all_type_pred.extend(
                type_preds.cpu().numpy()
            )

            all_category_true.extend(
                category_ids.cpu().numpy()
            )

            all_category_pred.extend(
                category_preds.cpu().numpy()
            )

    # --------------------------------------------------------
    # Convert to NumPy
    # --------------------------------------------------------

    all_type_true = np.array(
        all_type_true
    )

    all_type_pred = np.array(
        all_type_pred
    )

    all_category_true = np.array(
        all_category_true
    )

    all_category_pred = np.array(
        all_category_pred
    )

    # --------------------------------------------------------
    # Type metrics
    # --------------------------------------------------------

    type_accuracy = accuracy_score(
        all_type_true,
        all_type_pred
    )

    type_macro_f1 = f1_score(
        all_type_true,
        all_type_pred,
        average="macro",
        zero_division=0
    )

    # --------------------------------------------------------
    # Category metrics
    # --------------------------------------------------------

    category_accuracy = accuracy_score(
        all_category_true,
        all_category_pred
    )

    # Only categories actually present in validation
    present_labels = np.unique(
        all_category_true
    )

    category_macro_f1 = f1_score(
        all_category_true,
        all_category_pred,
        labels=present_labels,
        average="macro",
        zero_division=0
    )

    average_loss = (
        total_loss / len(loader)
    )

    return {
        "loss": average_loss,
        "type_accuracy": type_accuracy,
        "type_macro_f1": type_macro_f1,
        "category_accuracy": category_accuracy,
        "category_macro_f1": category_macro_f1,
        "type_true": all_type_true,
        "type_pred": all_type_pred,
        "category_true": all_category_true,
        "category_pred": all_category_pred
    }


# ============================================================
# 3. TRAINING LOOP
# ============================================================

print("=" * 70)
print("STARTING WHATSAPP MÚRIL FINE-TUNING")
print("=" * 70)

for epoch in range(NUM_EPOCHS):

    model.train()

    running_loss = 0.0

    train_type_true = []
    train_type_pred = []

    train_category_true = []
    train_category_pred = []

    for batch in whatsapp_train_loader:

        # ----------------------------------------------------
        # Move batch to GPU / device
        # ----------------------------------------------------

        input_ids = batch[
            "input_ids"
        ].to(
            device,
            non_blocking=True
        )

        attention_mask = batch[
            "attention_mask"
        ].to(
            device,
            non_blocking=True
        )

        type_ids = batch[
            "type_label"
        ].to(
            device,
            non_blocking=True
        )

        category_ids = batch[
            "category_label"
        ].to(
            device,
            non_blocking=True
        )

        # ----------------------------------------------------
        # Clear old gradients
        # ----------------------------------------------------

        whatsapp_optimizer.zero_grad(
            set_to_none=True
        )

        # ----------------------------------------------------
        # Forward pass
        # ----------------------------------------------------

        type_logits, category_logits = model(
            input_ids,
            attention_mask
        )

        # ----------------------------------------------------
        # Calculate losses
        # ----------------------------------------------------

        type_loss = whatsapp_type_loss_fn(
            type_logits,
            type_ids
        )

        category_loss = whatsapp_category_loss_fn(
            category_logits,
            category_ids
        )

        total_loss = (
            type_loss
            + category_loss
        )

        # ----------------------------------------------------
        # Backpropagation
        # ----------------------------------------------------

        total_loss.backward()

        # ----------------------------------------------------
        # Gradient clipping
        # ----------------------------------------------------

        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            max_norm=1.0
        )

        # ----------------------------------------------------
        # Update weights
        # ----------------------------------------------------

        whatsapp_optimizer.step()

        running_loss += total_loss.item()

        # ----------------------------------------------------
        # Save predictions for training metrics
        # ----------------------------------------------------

        type_preds = torch.argmax(
            type_logits,
            dim=1
        )

        category_preds = torch.argmax(
            category_logits,
            dim=1
        )

        train_type_true.extend(
            type_ids.detach().cpu().numpy()
        )

        train_type_pred.extend(
            type_preds.detach().cpu().numpy()
        )

        train_category_true.extend(
            category_ids.detach().cpu().numpy()
        )

        train_category_pred.extend(
            category_preds.detach().cpu().numpy()
        )

    # ========================================================
    # TRAINING METRICS
    # ========================================================

    train_loss = (
        running_loss /
        len(whatsapp_train_loader)
    )

    train_type_accuracy = accuracy_score(
        train_type_true,
        train_type_pred
    )

    train_category_accuracy = accuracy_score(
        train_category_true,
        train_category_pred
    )

    # ========================================================
    # VALIDATION
    # ========================================================

    val_metrics = evaluate_whatsapp(
        whatsapp_val_loader
    )

    # ========================================================
    # DISPLAY RESULTS
    # ========================================================

    print("\n" + "-" * 70)

    print(
        f"Epoch {epoch + 1}/{NUM_EPOCHS}"
    )

    print(
        f"Train Loss: "
        f"{train_loss:.4f}"
    )

    print(
        f"Train Type Acc: "
        f"{train_type_accuracy * 100:.2f}%"
    )

    print(
        f"Train Category Acc: "
        f"{train_category_accuracy * 100:.2f}%"
    )

    print(
        f"Val Loss: "
        f"{val_metrics['loss']:.4f}"
    )

    print(
        f"Val Type Acc: "
        f"{val_metrics['type_accuracy'] * 100:.2f}%"
    )

    print(
        f"Val Type Macro-F1: "
        f"{val_metrics['type_macro_f1']:.4f}"
    )

    print(
        f"Val Category Acc: "
        f"{val_metrics['category_accuracy'] * 100:.2f}%"
    )

    print(
        f"Val Category Macro-F1: "
        f"{val_metrics['category_macro_f1']:.4f}"
    )

    # ========================================================
    # SAVE BEST MODEL
    # ========================================================

    current_f1 = (
        val_metrics["category_macro_f1"]
    )

    if current_f1 > best_val_macro_f1:

        best_val_macro_f1 = current_f1

        best_val_accuracy = (
            val_metrics["category_accuracy"]
        )

        epochs_without_improvement = 0

        torch.save(
            model.state_dict(),
            BEST_WHATSAPP_MODEL_PATH
        )

        print(
            "\n✅ NEW BEST MODEL SAVED"
        )

        print(
            f"Best Val Category Macro-F1: "
            f"{best_val_macro_f1:.4f}"
        )

        print(
            f"Best Val Category Accuracy: "
            f"{best_val_accuracy * 100:.2f}%"
        )

    else:

        epochs_without_improvement += 1

        print(
            f"\nNo improvement."
            f" Patience: "
            f"{epochs_without_improvement}/{patience}"
        )

    # ========================================================
    # EARLY STOPPING
    # ========================================================

    if epochs_without_improvement >= patience:

        print(
            "\n⏹ Early stopping triggered."
        )

        break


# ============================================================
# 4. LOAD BEST WHATSAPP CHECKPOINT
# ============================================================

print("\n" + "=" * 70)
print("LOADING BEST WHATSAPP CHECKPOINT")
print("=" * 70)

model.load_state_dict(
    torch.load(
        BEST_WHATSAPP_MODEL_PATH,
        map_location=device
    )
)

model = model.to(device)

print(
    "Best WhatsApp model loaded successfully!"
)

print(
    f"Best validation category accuracy: "
    f"{best_val_accuracy * 100:.2f}%"
)

print(
    f"Best validation category macro-F1: "
    f"{best_val_macro_f1:.4f}"
)

======================================================================
STARTING WHATSAPP MÚRIL FINE-TUNING
======================================================================

----------------------------------------------------------------------
Epoch 1/6
Train Loss: 0.1741
Train Type Acc: 99.96%
Train Category Acc: 98.47%
Val Loss: 1.3311
Val Type Acc: 99.93%
Val Type Macro-F1: 0.9907
Val Category Acc: 78.35%
Val Category Macro-F1: 0.6401

✅ NEW BEST MODEL SAVED
Best Val Category Macro-F1: 0.6401
Best Val Category Accuracy: 78.35%

----------------------------------------------------------------------
Epoch 2/6
Train Loss: 0.0534
Train Type Acc: 100.00%
Train Category Acc: 99.68%
Val Loss: 1.6645
Val Type Acc: 99.79%
Val Type Macro-F1: 0.9731
Val Category Acc: 77.42%
Val Category Macro-F1: 0.6201

No improvement. Patience: 1/2

----------------------------------------------------------------------
Epoch 3/6
Train Loss: 0.0246
Train Type Acc: 100.00%
Train Category Acc: 99.86%
Val Loss: 1.7947
Val Type Acc: 99.86%
Val Type Macro-F1: 0.9818
Val Category Acc: 76.99%
Val Category Macro-F1: 0.6180

No improvement. Patience: 2/2

⏹ Early stopping triggered.

======================================================================
LOADING BEST WHATSAPP CHECKPOINT
======================================================================
Best WhatsApp model loaded successfully!
Best validation category accuracy: 78.35%
Best validation category macro-F1: 0.6401

In [28]:
# ============================================================
# STEP 26 — REALISTIC WHATSAPP TEST
# ============================================================

import pandas as pd
import numpy as np
import torch

from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import (
    accuracy_score,
    classification_report
)


# ============================================================
# 1. REALISTIC WHATSAPP TEST MESSAGES
# ============================================================

realistic_test_data = [

    # ---------------- FOOD ----------------
    ("yaar 250 ka pizza mangaya", "Food", "Expense"),
    ("aaj 180 ka burger khaya", "Food", "Expense"),
    ("swiggy pe 420 ka dinner order kiya", "Food", "Expense"),
    ("bhai chai aur snacks pe 90 rupaye gaye", "Food", "Expense"),
    ("250 ka paneer order kar diya", "Food", "Expense"),

    # ---------------- APPAREL ----------------
    ("amazon se 1800 ke shoes liye", "Apparel", "Expense"),
    ("bhai 1200 ki tshirt kharidi", "Apparel", "Expense"),
    ("aaj 900 ka kurta liya", "Apparel", "Expense"),
    ("1500 ki jeans le li", "Apparel", "Expense"),

    # ---------------- HEALTH ----------------
    ("doctor ko 600 diye", "Health", "Expense"),
    ("medicine pe 350 kharch hue", "Health", "Expense"),
    ("bhai 1200 ki medicines li", "Health", "Expense"),
    ("eye checkup ka 800 laga", "Health", "Expense"),

    # ---------------- TRANSPORTATION ----------------
    ("uber se ghar aaya 220", "Transportation", "Expense"),
    ("aaj auto ke 120 diye", "Transportation", "Expense"),
    ("metro ka 60 ka ticket liya", "Transportation", "Expense"),
    ("cab pe 450 kharch hue", "Transportation", "Expense"),

    # ---------------- SUBSCRIPTION ----------------
    ("netflix ka 199 wala plan renew kiya", "Subscription", "Expense"),
    ("spotify ke 119 rupaye diye", "Subscription", "Expense"),
    ("bhai mobile recharge 299 ka kiya", "Subscription", "Expense"),
    ("tata play recharge 350 ka hua", "Subscription", "Expense"),

    # ---------------- HOUSEHOLD ----------------
    ("ghar ke liye 1200 ka bedsheet liya", "Household", "Expense"),
    ("500 ke cleaning supplies liye", "Household", "Expense"),
    ("bhai 300 ka bulb aur switch liya", "Household", "Expense"),
    ("ghar ke saman pe 900 lage", "Household", "Expense"),

    # ---------------- INVESTMENT ----------------
    ("bhai 5000 mutual fund me daale", "Investment", "Expense"),
    ("aaj 2000 ka sip kiya", "Investment", "Expense"),
    ("zerodha me 3000 invest kiye", "Investment", "Expense"),

    # ---------------- GIFT ----------------
    ("friend ke birthday pe 700 ka gift liya", "Gift", "Expense"),
    ("bhai shaadi ke gift pe 1500 lage", "Gift", "Expense"),

    # ---------------- EDUCATION ----------------
    ("course ke 2000 diye", "Education", "Expense"),
    ("college form ke 500 lage", "Education", "Expense"),

    # ---------------- LEISURE ----------------
    ("aaj movie ke 500 lage", "Leisure", "Expense"),
    ("pvr me 700 kharch hue", "Leisure", "Expense"),
    ("weekend outing pe 1000 gaye", "Leisure", "Expense"),

    # ---------------- BEAUTY ----------------
    ("haircut ke 300 diye", "Beauty", "Expense"),
    ("salon pe 800 kharch hue", "Beauty", "Expense"),

    # ---------------- FAMILY ----------------
    ("mummy ke liye 1500 ka saman liya", "Family", "Expense"),
    ("bhai ko 500 ka gift diya", "Family", "Expense"),

    # ---------------- FESTIVALS ----------------
    ("diwali ke saman pe 1200 kharch hue", "Festivals", "Expense"),
    ("puja ka saman 600 ka liya", "Festivals", "Expense"),

    # ---------------- OTHER ----------------
    ("yaar 250 ka random expense ho gaya", "Other", "Expense"),
    ("500 ka miscellaneous kharcha ho gaya", "Other", "Expense"),

    # ---------------- SALARY ----------------
    ("aaj salary 45000 aa gayi", "Salary", "Income"),
    ("bhai salary credit ho gayi 50000", "Salary", "Income"),
]


realistic_test_df = pd.DataFrame(
    realistic_test_data,
    columns=[
        "text",
        "category",
        "type"
    ]
)


print("=" * 70)
print("REALISTIC WHATSAPP TEST SET")
print("=" * 70)

print(
    "Number of messages:",
    len(realistic_test_df)
)

print(
    "\nCategory distribution:"
)

print(
    realistic_test_df["category"].value_counts()
)


# ============================================================
# 2. CREATE LABEL MAPPINGS
# ============================================================

category_to_id = {
    label: idx
    for idx, label in enumerate(category_labels)
}

type_to_id = {
    label: idx
    for idx, label in enumerate(type_labels)
}


realistic_test_df["category_id"] = (
    realistic_test_df["category"]
    .map(category_to_id)
)

realistic_test_df["type_id"] = (
    realistic_test_df["type"]
    .map(type_to_id)
)


print("\n" + "=" * 70)
print("LABEL CHECK")
print("=" * 70)

print(
    "Missing category IDs:",
    realistic_test_df["category_id"].isna().sum()
)

print(
    "Missing type IDs:",
    realistic_test_df["type_id"].isna().sum()
)


# ============================================================
# 3. DATASET
# ============================================================

class RealisticWhatsAppDataset(Dataset):

    def __init__(
        self,
        df,
        tokenizer,
        max_length=32
    ):

        self.df = df.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):

        return len(self.df)

    def __getitem__(self, idx):

        row = self.df.iloc[idx]

        encoded = self.tokenizer(
            row["text"],
            padding="max_length",
            truncation=True,
            max_length=self.max_length,
            return_tensors="pt"
        )

        return {
            "input_ids": encoded[
                "input_ids"
            ].squeeze(0),

            "attention_mask": encoded[
                "attention_mask"
            ].squeeze(0),

            "type_label": torch.tensor(
                int(row["type_id"]),
                dtype=torch.long
            ),

            "category_label": torch.tensor(
                int(row["category_id"]),
                dtype=torch.long
            ),

            "text": row["text"]
        }


# ============================================================
# 4. CREATE TEST LOADER
# ============================================================

realistic_test_dataset = RealisticWhatsAppDataset(
    realistic_test_df,
    tokenizer,
    max_length=32
)

realistic_test_loader = DataLoader(
    realistic_test_dataset,
    batch_size=16,
    shuffle=False
)


print("\n" + "=" * 70)
print("TEST DATALOADER")
print("=" * 70)

print(
    "Dataset size:",
    len(realistic_test_dataset)
)

print(
    "Batches:",
    len(realistic_test_loader)
)


# ============================================================
# 5. EVALUATION FUNCTION
# ============================================================

def evaluate_model_on_realistic_test(model_path):

    # Load model checkpoint
    model.load_state_dict(
        torch.load(
            model_path,
            map_location=device
        )
    )

    model.to(device)
    model.eval()

    all_type_true = []
    all_type_pred = []

    all_category_true = []
    all_category_pred = []

    all_texts = []

    with torch.no_grad():

        for batch in realistic_test_loader:

            input_ids = batch[
                "input_ids"
            ].to(
                device,
                non_blocking=True
            )

            attention_mask = batch[
                "attention_mask"
            ].to(
                device,
                non_blocking=True
            )

            type_ids = batch[
                "type_label"
            ].to(
                device,
                non_blocking=True
            )

            category_ids = batch[
                "category_label"
            ].to(
                device,
                non_blocking=True
            )

            # Forward pass
            type_logits, category_logits = model(
                input_ids,
                attention_mask
            )

            # Predictions
            type_preds = torch.argmax(
                type_logits,
                dim=1
            )

            category_preds = torch.argmax(
                category_logits,
                dim=1
            )

            # Store predictions
            all_type_true.extend(
                type_ids.cpu().numpy()
            )

            all_type_pred.extend(
                type_preds.cpu().numpy()
            )

            all_category_true.extend(
                category_ids.cpu().numpy()
            )

            all_category_pred.extend(
                category_preds.cpu().numpy()
            )

            all_texts.extend(
                batch["text"]
            )

    return {
        "texts": all_texts,
        "type_true": np.array(all_type_true),
        "type_pred": np.array(all_type_pred),
        "category_true": np.array(
            all_category_true
        ),
        "category_pred": np.array(
            all_category_pred
        )
    }


# ============================================================
# 6. EVALUATE ORIGINAL MODEL
# ============================================================

print("\n" + "=" * 70)
print("TESTING ORIGINAL MODEL")
print("=" * 70)

original_results = evaluate_model_on_realistic_test(
    "/kaggle/working/muril_original_best.pt"
)

original_category_accuracy = accuracy_score(
    original_results["category_true"],
    original_results["category_pred"]
)

original_type_accuracy = accuracy_score(
    original_results["type_true"],
    original_results["type_pred"]
)

print(
    "Original Category Accuracy:",
    f"{original_category_accuracy * 100:.2f}%"
)

print(
    "Original Type Accuracy:",
    f"{original_type_accuracy * 100:.2f}%"
)


# ============================================================
# 7. EVALUATE WHATSAPP MODEL
# ============================================================

print("\n" + "=" * 70)
print("TESTING WHATSAPP-FINE-TUNED MODEL")
print("=" * 70)

whatsapp_results = evaluate_model_on_realistic_test(
    "/kaggle/working/muril_whatsapp_best.pt"
)

whatsapp_category_accuracy = accuracy_score(
    whatsapp_results["category_true"],
    whatsapp_results["category_pred"]
)

whatsapp_type_accuracy = accuracy_score(
    whatsapp_results["type_true"],
    whatsapp_results["type_pred"]
)

print(
    "WhatsApp Category Accuracy:",
    f"{whatsapp_category_accuracy * 100:.2f}%"
)

print(
    "WhatsApp Type Accuracy:",
    f"{whatsapp_type_accuracy * 100:.2f}%"
)


# ============================================================
# 8. COMPARISON
# ============================================================

print("\n" + "=" * 70)
print("MODEL COMPARISON")
print("=" * 70)

print(
    f"Original Model Category Accuracy:"
    f" {original_category_accuracy * 100:.2f}%"
)

print(
    f"WhatsApp Model Category Accuracy:"
    f" {whatsapp_category_accuracy * 100:.2f}%"
)

print(
    f"Original Model Type Accuracy:"
    f" {original_type_accuracy * 100:.2f}%"
)

print(
    f"WhatsApp Model Type Accuracy:"
    f" {whatsapp_type_accuracy * 100:.2f}%"
)


# ============================================================
# 9. SHOW EVERY PREDICTION
# ============================================================

comparison_df = realistic_test_df[
    [
        "text",
        "category",
        "type"
    ]
].copy()

comparison_df["Original Prediction"] = [
    category_labels[x]
    for x in original_results[
        "category_pred"
    ]
]

comparison_df["WhatsApp Prediction"] = [
    category_labels[x]
    for x in whatsapp_results[
        "category_pred"
    ]
]

comparison_df["Original Correct"] = (
    comparison_df["category"]
    ==
    comparison_df["Original Prediction"]
)

comparison_df["WhatsApp Correct"] = (
    comparison_df["category"]
    ==
    comparison_df["WhatsApp Prediction"]
)


print("\n" + "=" * 70)
print("ALL TEST PREDICTIONS")
print("=" * 70)

display(
    comparison_df
)


# ============================================================
# 10. CLASSIFICATION REPORTS
# ============================================================

print("\n" + "=" * 70)
print("ORIGINAL MODEL — CLASSIFICATION REPORT")
print("=" * 70)

print(
    classification_report(
        original_results["category_true"],
        original_results["category_pred"],
        labels=list(range(len(category_labels))),
        target_names=category_labels,
        zero_division=0
    )
)


print("\n" + "=" * 70)
print("WHATSAPP MODEL — CLASSIFICATION REPORT")
print("=" * 70)

print(
    classification_report(
        whatsapp_results["category_true"],
        whatsapp_results["category_pred"],
        labels=list(range(len(category_labels))),
        target_names=category_labels,
        zero_division=0
    )
)


# ============================================================
# 11. SHOW ONLY WRONG PREDICTIONS
# ============================================================

wrong_predictions = comparison_df[
    ~comparison_df["WhatsApp Correct"]
].copy()

print("\n" + "=" * 70)
print("WHATSAPP MODEL — WRONG PREDICTIONS")
print("=" * 70)

print(
    "Wrong:",
    len(wrong_predictions)
)

display(
    wrong_predictions
)

======================================================================
REALISTIC WHATSAPP TEST SET
======================================================================
Number of messages: 45

Category distribution:
category
Food              5
Apparel           4
Health            4
Transportation    4
Subscription      4
Household         4
Investment        3
Leisure           3
Gift              2
Education         2
Beauty            2
Family            2
Festivals         2
Other             2
Salary            2
Name: count, dtype: int64

======================================================================
LABEL CHECK
======================================================================
Missing category IDs: 0
Missing type IDs: 0

======================================================================
TEST DATALOADER
======================================================================
Dataset size: 45
Batches: 3

======================================================================
TESTING ORIGINAL MODEL
======================================================================
Original Category Accuracy: 40.00%
Original Type Accuracy: 95.56%

======================================================================
TESTING WHATSAPP-FINE-TUNED MODEL
======================================================================
WhatsApp Category Accuracy: 44.44%
WhatsApp Type Accuracy: 91.11%

======================================================================
MODEL COMPARISON
======================================================================
Original Model Category Accuracy: 40.00%
WhatsApp Model Category Accuracy: 44.44%
Original Model Type Accuracy: 95.56%
WhatsApp Model Type Accuracy: 91.11%

======================================================================
ALL TEST PREDICTIONS
======================================================================

,text,category,type,Original Prediction,WhatsApp Prediction,Original Correct,WhatsApp Correct
0,yaar 250 ka pizza mangaya,Food,Expense,Food,Food,True,True
1,aaj 180 ka burger khaya,Food,Expense,Food,Food,True,True
2,swiggy pe 420 ka dinner order kiya,Food,Expense,Food,Household,True,False
3,bhai chai aur snacks pe 90 rupaye gaye,Food,Expense,Food,Food,True,True
4,250 ka paneer order kar diya,Food,Expense,Food,Food,True,True
5,amazon se 1800 ke shoes liye,Apparel,Expense,Apparel,Family,True,False
6,bhai 1200 ki tshirt kharidi,Apparel,Expense,Household,Apparel,False,True
7,aaj 900 ka kurta liya,Apparel,Expense,Food,Food,False,False
8,1500 ki jeans le li,Apparel,Expense,Apparel,Apparel,True,True
9,doctor ko 600 diye,Health,Expense,Other,Health,False,True
10,medicine pe 350 kharch hue,Health,Expense,Food,Food,False,False
11,bhai 1200 ki medicines li,Health,Expense,Subscription,Health,False,True
12,eye checkup ka 800 laga,Health,Expense,Health,Health,True,True
13,uber se ghar aaya 220,Transportation,Expense,Transportation,Household,True,False
14,aaj auto ke 120 diye,Transportation,Expense,Other,Transportation,False,True
15,metro ka 60 ka ticket liya,Transportation,Expense,Other,Other,False,False
16,cab pe 450 kharch hue,Transportation,Expense,Other,Food,False,False
17,netflix ka 199 wala plan renew kiya,Subscription,Expense,Other,Health,False,False
18,spotify ke 119 rupaye diye,Subscription,Expense,Subscription,Household,True,False
19,bhai mobile recharge 299 ka kiya,Subscription,Expense,Subscription,Subscription,True,True
20,tata play recharge 350 ka hua,Subscription,Expense,Food,Food,False,False
21,ghar ke liye 1200 ka bedsheet liya,Household,Expense,Transportation,Household,False,True
22,500 ke cleaning supplies liye,Household,Expense,Household,Apparel,True,False
23,bhai 300 ka bulb aur switch liya,Household,Expense,Household,Household,True,True
24,ghar ke saman pe 900 lage,Household,Expense,Transportation,Transportation,False,False
25,bhai 5000 mutual fund me daale,Investment,Expense,Investment,Investment,True,True
26,aaj 2000 ka sip kiya,Investment,Expense,Subscription,Household,False,False
27,zerodha me 3000 invest kiye,Investment,Expense,Subscription,Other,False,False
28,friend ke birthday pe 700 ka gift liya,Gift,Expense,Gift,Gift,True,True
29,bhai shaadi ke gift pe 1500 lage,Gift,Expense,Gift,Gift,True,True
30,course ke 2000 diye,Education,Expense,Other,Family,False,False
31,college form ke 500 lage,Education,Expense,Household,Family,False,False
32,aaj movie ke 500 lage,Leisure,Expense,Subscription,Leisure,False,True
33,pvr me 700 kharch hue,Leisure,Expense,Other,Household,False,False
34,weekend outing pe 1000 gaye,Leisure,Expense,Subscription,Transportation,False,False
35,haircut ke 300 diye,Beauty,Expense,Other,Beauty,False,True
36,salon pe 800 kharch hue,Beauty,Expense,Household,Household,False,False
37,mummy ke liye 1500 ka saman liya,Family,Expense,Other,Family,False,True
38,bhai ko 500 ka gift diya,Family,Expense,Gift,Other,False,False
39,diwali ke saman pe 1200 kharch hue,Festivals,Expense,Investment,Investment,False,False
40,puja ka saman 600 ka liya,Festivals,Expense,Food,Festivals,False,True
41,yaar 250 ka random expense ho gaya,Other,Expense,Other,Leisure,True,False
42,500 ka miscellaneous kharcha ho gaya,Other,Expense,Other,Leisure,True,False
43,aaj salary 45000 aa gayi,Salary,Income,Other,Other,False,False
44,bhai salary credit ho gayi 50000,Salary,Income,Other,Other,False,False

======================================================================
ORIGINAL MODEL — CLASSIFICATION REPORT
======================================================================
                precision    recall  f1-score   support

       Apparel       1.00      0.50      0.67         4
        Beauty       0.00      0.00      0.00         2
     Education       0.00      0.00      0.00         2
        Family       0.00      0.00      0.00         2
     Festivals       0.00      0.00      0.00         2
          Food       0.56      1.00      0.71         5
          Gift       0.67      1.00      0.80         2
        Health       1.00      0.25      0.40         4
     Household       0.40      0.50      0.44         4
    Investment       0.50      0.33      0.40         3
       Leisure       0.00      0.00      0.00         3
         Other       0.15      1.00      0.27         2
        Salary       0.00      0.00      0.00         2
  Subscription       0.29      0.50      0.36         4
Transportation       0.33      0.25      0.29         4

      accuracy                           0.40        45
     macro avg       0.33      0.36      0.29        45
  weighted avg       0.40      0.40      0.35        45


======================================================================
WHATSAPP MODEL — CLASSIFICATION REPORT
======================================================================
                precision    recall  f1-score   support

       Apparel       0.67      0.50      0.57         4
        Beauty       1.00      0.50      0.67         2
     Education       0.00      0.00      0.00         2
        Family       0.25      0.50      0.33         2
     Festivals       1.00      0.50      0.67         2
          Food       0.50      0.80      0.62         5
          Gift       1.00      1.00      1.00         2
        Health       0.75      0.75      0.75         4
     Household       0.25      0.50      0.33         4
    Investment       0.50      0.33      0.40         3
       Leisure       0.33      0.33      0.33         3
         Other       0.00      0.00      0.00         2
        Salary       0.00      0.00      0.00         2
  Subscription       1.00      0.25      0.40         4
Transportation       0.33      0.25      0.29         4

      accuracy                           0.44        45
     macro avg       0.51      0.41      0.42        45
  weighted avg       0.52      0.44      0.44        45


======================================================================
WHATSAPP MODEL — WRONG PREDICTIONS
======================================================================
Wrong: 25

,text,category,type,Original Prediction,WhatsApp Prediction,Original Correct,WhatsApp Correct
2,swiggy pe 420 ka dinner order kiya,Food,Expense,Food,Household,True,False
5,amazon se 1800 ke shoes liye,Apparel,Expense,Apparel,Family,True,False
7,aaj 900 ka kurta liya,Apparel,Expense,Food,Food,False,False
10,medicine pe 350 kharch hue,Health,Expense,Food,Food,False,False
13,uber se ghar aaya 220,Transportation,Expense,Transportation,Household,True,False
15,metro ka 60 ka ticket liya,Transportation,Expense,Other,Other,False,False
16,cab pe 450 kharch hue,Transportation,Expense,Other,Food,False,False
17,netflix ka 199 wala plan renew kiya,Subscription,Expense,Other,Health,False,False
18,spotify ke 119 rupaye diye,Subscription,Expense,Subscription,Household,True,False
20,tata play recharge 350 ka hua,Subscription,Expense,Food,Food,False,False
22,500 ke cleaning supplies liye,Household,Expense,Household,Apparel,True,False
24,ghar ke saman pe 900 lage,Household,Expense,Transportation,Transportation,False,False
26,aaj 2000 ka sip kiya,Investment,Expense,Subscription,Household,False,False
27,zerodha me 3000 invest kiye,Investment,Expense,Subscription,Other,False,False
30,course ke 2000 diye,Education,Expense,Other,Family,False,False
31,college form ke 500 lage,Education,Expense,Household,Family,False,False
33,pvr me 700 kharch hue,Leisure,Expense,Other,Household,False,False
34,weekend outing pe 1000 gaye,Leisure,Expense,Subscription,Transportation,False,False
36,salon pe 800 kharch hue,Beauty,Expense,Household,Household,False,False
38,bhai ko 500 ka gift diya,Family,Expense,Gift,Other,False,False
39,diwali ke saman pe 1200 kharch hue,Festivals,Expense,Investment,Investment,False,False
41,yaar 250 ka random expense ho gaya,Other,Expense,Other,Leisure,True,False
42,500 ka miscellaneous kharcha ho gaya,Other,Expense,Other,Leisure,True,False
43,aaj salary 45000 aa gayi,Salary,Income,Other,Other,False,False
44,bhai salary credit ho gayi 50000,Salary,Income,Other,Other,False,False

In [29]:
# ============================================================
# STEP 27 — HYBRID WHATSAPP TRANSACTION EXTRACTOR
# ============================================================

import re
import pandas as pd


# ============================================================
# 1. CATEGORY KEYWORDS
# ============================================================

CATEGORY_KEYWORDS = {

    "Food": [
        "pizza",
        "burger",
        "food",
        "dinner",
        "lunch",
        "breakfast",
        "chai",
        "tea",
        "snacks",
        "paneer",
        "swiggy",
        "zomato",
        "restaurant",
        "groceries",
        "grocery"
    ],

    "Apparel": [
        "shoes",
        "shoe",
        "tshirt",
        "t-shirt",
        "shirt",
        "jeans",
        "kurta",
        "trouser",
        "dress",
        "clothes",
        "jacket",
        "sweater",
        "sandal"
    ],

    "Health": [
        "doctor",
        "medicine",
        "medicines",
        "medical",
        "hospital",
        "checkup",
        "check-up",
        "clinic",
        "tablet",
        "syrup",
        "eye checkup",
        "dentist",
        "therapy"
    ],

    "Transportation": [
        "uber",
        "ola",
        "auto",
        "metro",
        "cab",
        "taxi",
        "bus",
        "train",
        "rickshaw",
        "petrol",
        "diesel",
        "fuel",
        "parking"
    ],

    "Subscription": [
        "netflix",
        "spotify",
        "amazon prime",
        "prime",
        "subscription",
        "recharge",
        "mobile recharge",
        "tata play",
        "hotstar",
        "youtube premium",
        "membership"
    ],

    "Household": [
        "bedsheet",
        "bed sheet",
        "cleaning",
        "cleaning supplies",
        "bulb",
        "switch",
        "household",
        "home",
        "ghar ka saman",
        "ghar ke saman",
        "utensil",
        "crockery",
        "furniture",
        "mop",
        "bucket",
        "soap",
        "shampoo"
    ],

    "Investment": [
        "mutual fund",
        "mutual funds",
        "sip",
        "zerodha",
        "investment",
        "invest",
        "stock",
        "stocks",
        "share market",
        "shares",
        "equity",
        "fd",
        "fixed deposit",
        "rd",
        "recurring deposit"
    ],

    "Leisure": [
        "movie",
        "movies",
        "pvr",
        "cinema",
        "cinépolis",
        "carnival",
        "outing",
        "trip",
        "tour",
        "planetarium",
        "concert",
        "game",
        "gaming"
    ],

    "Beauty": [
        "haircut",
        "salon",
        "beauty",
        "facial",
        "parlour",
        "parlor",
        "spa",
        "manicure",
        "pedicure"
    ],

    "Education": [
        "course",
        "college",
        "school",
        "tuition",
        "exam",
        "form",
        "fees",
        "education",
        "class",
        "training"
    ],

    "Gift": [
        "gift",
        "present",
        "birthday gift",
        "wedding gift"
    ],

    "Family": [
        "mummy",
        "mom",
        "mother",
        "papa",
        "father",
        "brother",
        "sister",
        "family",
        "bhai ko",
        "mummy ke"
    ],

    "Festivals": [
        "diwali",
        "holi",
        "puja",
        "pooja",
        "festival",
        "rakhi",
        "eid",
        "navratri",
        "dussehra"
    ],

    "Salary": [
        "salary",
        "salary credit",
        "salary aa gayi",
        "paycheck",
        "income credited"
    ]
}


# ============================================================
# 2. AMOUNT EXTRACTION
# ============================================================

def extract_amount(text):

    text_lower = text.lower()

    # --------------------------------------------------------
    # Examples supported:
    # 250
    # 250 rs
    # rs 250
    # 250 rupees
    # 1,500
    # 1.5k
    # --------------------------------------------------------

    patterns = [

        # 1.5k / 2k / 10k
        r'(?<!\w)(\d+(?:\.\d+)?)\s*[kK]\b',

        # rs 250 / rs. 250 / ₹250
        r'(?:₹|rs\.?|inr)\s*([0-9]+(?:,[0-9]{3})*(?:\.[0-9]+)?)',

        # 250 rupees
        r'([0-9]+(?:,[0-9]{3})*(?:\.[0-9]+)?)\s*(?:rupees|rs)\b',

        # plain number
        r'(?<!\w)([0-9]+(?:,[0-9]{3})*(?:\.[0-9]+)?)(?!\w)'
    ]

    for pattern in patterns:

        match = re.search(
            pattern,
            text_lower
        )

        if match:

            raw_value = match.group(1)

            raw_value = raw_value.replace(
                ",",
                ""
            )

            value = float(raw_value)

            # Convert k notation
            if re.search(
                r'[kK]\b',
                match.group(0)
            ):
                value *= 1000

            return value

    return None


# ============================================================
# 3. CATEGORY RULE ENGINE
# ============================================================

def rule_based_category(text):

    text_lower = text.lower()

    matches = []

    for category, keywords in CATEGORY_KEYWORDS.items():

        for keyword in keywords:

            if keyword in text_lower:

                matches.append(
                    (
                        category,
                        len(keyword)
                    )
                )

    if not matches:
        return None

    # Longer keyword generally means
    # more specific matching.
    matches.sort(
        key=lambda x: x[1],
        reverse=True
    )

    return matches[0][0]


# ============================================================
# 4. TYPE DETECTION
# ============================================================

def rule_based_type(text):

    text_lower = text.lower()

    income_words = [
        "salary",
        "salary credit",
        "credited",
        "income",
        "received",
        "received money",
        "cashback",
        "refund",
        "bonus"
    ]

    for word in income_words:

        if word in text_lower:
            return "Income"

    return "Expense"


# ============================================================
# 5. COMPLETE TRANSACTION PARSER
# ============================================================

def parse_whatsapp_message(text):

    amount = extract_amount(text)

    category = rule_based_category(text)

    transaction_type = rule_based_type(text)

    return {
        "text": text,
        "amount": amount,
        "category": category,
        "type": transaction_type
    }


# ============================================================
# 6. TEST ON EXAMPLES
# ============================================================

example_messages = [

    "yaar 250 ka pizza mangaya",

    "amazon se 1800 ke shoes liye",

    "doctor ko 600 diye",

    "uber se ghar aaya 220",

    "netflix ka 199 wala plan renew kiya",

    "bhai 5000 mutual fund me daale",

    "aaj salary 45000 aa gayi",

    "haircut ke 300 diye",

    "diwali ke saman pe 1200 kharch hue"
]


print("=" * 70)
print("HYBRID WHATSAPP PARSER TEST")
print("=" * 70)

for message in example_messages:

    result = parse_whatsapp_message(
        message
    )

    print("\nMessage:", message)

    print(
        "Amount:",
        result["amount"]
    )

    print(
        "Category:",
        result["category"]
    )

    print(
        "Type:",
        result["type"]
    )

======================================================================
HYBRID WHATSAPP PARSER TEST
======================================================================

Message: yaar 250 ka pizza mangaya
Amount: 250.0
Category: Food
Type: Expense

Message: amazon se 1800 ke shoes liye
Amount: 1800.0
Category: Apparel
Type: Expense

Message: doctor ko 600 diye
Amount: 600.0
Category: Health
Type: Expense

Message: uber se ghar aaya 220
Amount: 220.0
Category: Transportation
Type: Expense

Message: netflix ka 199 wala plan renew kiya
Amount: 199.0
Category: Subscription
Type: Expense

Message: bhai 5000 mutual fund me daale
Amount: 5000.0
Category: Investment
Type: Expense

Message: aaj salary 45000 aa gayi
Amount: 45000.0
Category: Salary
Type: Income

Message: haircut ke 300 diye
Amount: 300.0
Category: Beauty
Type: Expense

Message: diwali ke saman pe 1200 kharch hue
Amount: 1200.0
Category: Festivals
Type: Expense

In [30]:
# ============================================================
# STEP 28 — BENCHMARK HYBRID PARSER ON 45 TEST MESSAGES
# ============================================================

import pandas as pd


# ============================================================
# 1. RUN PARSER ON EVERY TEST MESSAGE
# ============================================================

hybrid_results = []

for _, row in realistic_test_df.iterrows():

    result = parse_whatsapp_message(
        row["text"]
    )

    hybrid_results.append({

        "text": row["text"],

        "actual_category":
            row["category"],

        "predicted_category":
            result["category"],

        "actual_type":
            row["type"],

        "predicted_type":
            result["type"],

        "actual_amount":
            None,   # Our benchmark doesn't have
                    # a separate numeric amount column

        "extracted_amount":
            result["amount"]
    })


hybrid_results_df = pd.DataFrame(
    hybrid_results
)


# ============================================================
# 2. CATEGORY ACCURACY
# ============================================================

category_correct = (
    hybrid_results_df[
        "actual_category"
    ]
    ==
    hybrid_results_df[
        "predicted_category"
    ]
)

category_accuracy = (
    category_correct.mean()
)


# ============================================================
# 3. TYPE ACCURACY
# ============================================================

type_correct = (
    hybrid_results_df[
        "actual_type"
    ]
    ==
    hybrid_results_df[
        "predicted_type"
    ]
)

type_accuracy = (
    type_correct.mean()
)


# ============================================================
# 4. AMOUNT COVERAGE
# ============================================================

amount_extracted = (
    hybrid_results_df[
        "extracted_amount"
    ]
    .notna()
)

amount_coverage = (
    amount_extracted.mean()
)


# ============================================================
# 5. DISPLAY OVERALL RESULTS
# ============================================================

print("=" * 70)
print("HYBRID PARSER — 45 MESSAGE BENCHMARK")
print("=" * 70)

print(
    f"Category Accuracy: "
    f"{category_accuracy * 100:.2f}%"
)

print(
    f"Type Accuracy: "
    f"{type_accuracy * 100:.2f}%"
)

print(
    f"Amount Extraction Coverage: "
    f"{amount_coverage * 100:.2f}%"
)

print(
    "\nCorrect Categories:",
    category_correct.sum(),
    "/",
    len(hybrid_results_df)
)

print(
    "Correct Types:",
    type_correct.sum(),
    "/",
    len(hybrid_results_df)
)

print(
    "Amounts Extracted:",
    amount_extracted.sum(),
    "/",
    len(hybrid_results_df)
)


# ============================================================
# 6. DISPLAY ALL PREDICTIONS
# ============================================================

print("\n" + "=" * 70)
print("ALL HYBRID PREDICTIONS")
print("=" * 70)

display(
    hybrid_results_df[
        [
            "text",
            "actual_category",
            "predicted_category",
            "actual_type",
            "predicted_type",
            "extracted_amount"
        ]
    ]
)


# ============================================================
# 7. SHOW CATEGORY ERRORS
# ============================================================

hybrid_category_errors = (
    hybrid_results_df[
        ~category_correct
    ]
    .copy()
)


print("\n" + "=" * 70)
print("HYBRID CATEGORY ERRORS")
print("=" * 70)

print(
    "Wrong category predictions:",
    len(hybrid_category_errors)
)

display(
    hybrid_category_errors[
        [
            "text",
            "actual_category",
            "predicted_category"
        ]
    ]
)


# ============================================================
# 8. SHOW TYPE ERRORS
# ============================================================

hybrid_type_errors = (
    hybrid_results_df[
        ~type_correct
    ]
    .copy()
)


print("\n" + "=" * 70)
print("HYBRID TYPE ERRORS")
print("=" * 70)

print(
    "Wrong type predictions:",
    len(hybrid_type_errors)
)

display(
    hybrid_type_errors[
        [
            "text",
            "actual_type",
            "predicted_type"
        ]
    ]
)


# ============================================================
# 9. SHOW MESSAGES WHERE NO CATEGORY WAS FOUND
# ============================================================

no_category = hybrid_results_df[
    hybrid_results_df[
        "predicted_category"
    ].isna()
]


print("\n" + "=" * 70)
print("MESSAGES WITH NO RULE MATCH")
print("=" * 70)

print(
    "No category found:",
    len(no_category)
)

display(
    no_category[
        ["text"]
    ]
)

======================================================================
HYBRID PARSER — 45 MESSAGE BENCHMARK
======================================================================
Category Accuracy: 95.56%
Type Accuracy: 100.00%
Amount Extraction Coverage: 100.00%

Correct Categories: 43 / 45
Correct Types: 45 / 45
Amounts Extracted: 45 / 45

======================================================================
ALL HYBRID PREDICTIONS
======================================================================

,text,actual_category,predicted_category,actual_type,predicted_type,extracted_amount
0,yaar 250 ka pizza mangaya,Food,Food,Expense,Expense,250.0
1,aaj 180 ka burger khaya,Food,Food,Expense,Expense,180.0
2,swiggy pe 420 ka dinner order kiya,Food,Food,Expense,Expense,420.0
3,bhai chai aur snacks pe 90 rupaye gaye,Food,Food,Expense,Expense,90.0
4,250 ka paneer order kar diya,Food,Food,Expense,Expense,250.0
5,amazon se 1800 ke shoes liye,Apparel,Apparel,Expense,Expense,1800.0
6,bhai 1200 ki tshirt kharidi,Apparel,Apparel,Expense,Expense,1200.0
7,aaj 900 ka kurta liya,Apparel,Apparel,Expense,Expense,900.0
8,1500 ki jeans le li,Apparel,Apparel,Expense,Expense,1500.0
9,doctor ko 600 diye,Health,Health,Expense,Expense,600.0
10,medicine pe 350 kharch hue,Health,Health,Expense,Expense,350.0
11,bhai 1200 ki medicines li,Health,Health,Expense,Expense,1200.0
12,eye checkup ka 800 laga,Health,Health,Expense,Expense,800.0
13,uber se ghar aaya 220,Transportation,Transportation,Expense,Expense,220.0
14,aaj auto ke 120 diye,Transportation,Transportation,Expense,Expense,120.0
15,metro ka 60 ka ticket liya,Transportation,Transportation,Expense,Expense,60.0
16,cab pe 450 kharch hue,Transportation,Transportation,Expense,Expense,450.0
17,netflix ka 199 wala plan renew kiya,Subscription,Subscription,Expense,Expense,199.0
18,spotify ke 119 rupaye diye,Subscription,Subscription,Expense,Expense,119.0
19,bhai mobile recharge 299 ka kiya,Subscription,Subscription,Expense,Expense,299.0
20,tata play recharge 350 ka hua,Subscription,Subscription,Expense,Expense,350.0
21,ghar ke liye 1200 ka bedsheet liya,Household,Household,Expense,Expense,1200.0
22,500 ke cleaning supplies liye,Household,Household,Expense,Expense,500.0
23,bhai 300 ka bulb aur switch liya,Household,Household,Expense,Expense,300.0
24,ghar ke saman pe 900 lage,Household,Household,Expense,Expense,900.0
25,bhai 5000 mutual fund me daale,Investment,Investment,Expense,Expense,5000.0
26,aaj 2000 ka sip kiya,Investment,Investment,Expense,Expense,2000.0
27,zerodha me 3000 invest kiye,Investment,Investment,Expense,Expense,3000.0
28,friend ke birthday pe 700 ka gift liya,Gift,Gift,Expense,Expense,700.0
29,bhai shaadi ke gift pe 1500 lage,Gift,Gift,Expense,Expense,1500.0
30,course ke 2000 diye,Education,Education,Expense,Expense,2000.0
31,college form ke 500 lage,Education,Education,Expense,Expense,500.0
32,aaj movie ke 500 lage,Leisure,Leisure,Expense,Expense,500.0
33,pvr me 700 kharch hue,Leisure,Leisure,Expense,Expense,700.0
34,weekend outing pe 1000 gaye,Leisure,Leisure,Expense,Expense,1000.0
35,haircut ke 300 diye,Beauty,Beauty,Expense,Expense,300.0
36,salon pe 800 kharch hue,Beauty,Beauty,Expense,Expense,800.0
37,mummy ke liye 1500 ka saman liya,Family,Family,Expense,Expense,1500.0
38,bhai ko 500 ka gift diya,Family,Family,Expense,Expense,500.0
39,diwali ke saman pe 1200 kharch hue,Festivals,Festivals,Expense,Expense,1200.0
40,puja ka saman 600 ka liya,Festivals,Festivals,Expense,Expense,600.0
41,yaar 250 ka random expense ho gaya,Other,None,Expense,Expense,250.0
42,500 ka miscellaneous kharcha ho gaya,Other,None,Expense,Expense,500.0
43,aaj salary 45000 aa gayi,Salary,Salary,Income,Income,45000.0
44,bhai salary credit ho gayi 50000,Salary,Salary,Income,Income,50000.0

======================================================================
HYBRID CATEGORY ERRORS
======================================================================
Wrong category predictions: 2

                                    text actual_category predicted_category
41    yaar 250 ka random expense ho gaya           Other               None
42  500 ka miscellaneous kharcha ho gaya           Other               None

======================================================================
HYBRID TYPE ERRORS
======================================================================
Wrong type predictions: 0

Empty DataFrame
Columns: [text, actual_type, predicted_type]
Index: []

======================================================================
MESSAGES WITH NO RULE MATCH
======================================================================
No category found: 2

                                    text
41    yaar 250 ka random expense ho gaya
42  500 ka miscellaneous kharcha ho gaya

In [31]:
# ============================================================
# STEP 29 — FINAL HYBRID PARSER
# ============================================================

import re
import torch


# ============================================================
# 1. ADD GENERIC "OTHER" KEYWORDS
# ============================================================

CATEGORY_KEYWORDS["Other"] = [

    "random expense",
    "random kharcha",
    "miscellaneous",
    "miscellaneous expense",
    "misc expense",
    "misc kharcha",
    "other expense",
    "other kharcha",
    "random kharch",
    "miscellaneous kharch",
    "misc",
    "unplanned expense",
    "unplanned kharcha"
]


# ============================================================
# 2. IMPROVED CATEGORY RULE FUNCTION
# ============================================================

def rule_based_category(text):

    text_lower = text.lower()

    matches = []

    for category, keywords in CATEGORY_KEYWORDS.items():

        for keyword in keywords:

            if keyword in text_lower:

                matches.append(
                    (
                        category,
                        len(keyword)
                    )
                )

    if not matches:
        return None

    # Prefer the most specific / longest keyword
    matches.sort(
        key=lambda x: x[1],
        reverse=True
    )

    return matches[0][0]


# ============================================================
# 3. MÚRIL FALLBACK CLASSIFIER
# ============================================================

def muril_category_prediction(text):

    model.eval()

    encoded = tokenizer(
        text,
        padding="max_length",
        truncation=True,
        max_length=32,
        return_tensors="pt"
    )

    input_ids = encoded[
        "input_ids"
    ].to(device)

    attention_mask = encoded[
        "attention_mask"
    ].to(device)

    with torch.no_grad():

        type_logits, category_logits = model(
            input_ids,
            attention_mask
        )

        probabilities = torch.softmax(
            category_logits,
            dim=1
        )

        confidence, prediction = torch.max(
            probabilities,
            dim=1
        )

    predicted_category = category_labels[
        prediction.item()
    ]

    confidence_value = confidence.item()

    return (
        predicted_category,
        confidence_value
    )


# ============================================================
# 4. FINAL TRANSACTION PARSER
# ============================================================

def parse_whatsapp_message_final(text):

    # --------------------------------------------------------
    # Amount
    # --------------------------------------------------------

    amount = extract_amount(text)

    # --------------------------------------------------------
    # Type
    # --------------------------------------------------------

    transaction_type = rule_based_type(text)

    # --------------------------------------------------------
    # Rule-based category
    # --------------------------------------------------------

    category = rule_based_category(text)

    source = "rule"
    confidence = 1.0

    # --------------------------------------------------------
    # MuRIL fallback
    # --------------------------------------------------------

    if category is None:

        category, confidence = (
            muril_category_prediction(text)
        )

        source = "muril"

    return {

        "text": text,

        "amount": amount,

        "category": category,

        "type": transaction_type,

        "category_source": source,

        "category_confidence": confidence
    }


# ============================================================
# 5. TEST THE TWO PREVIOUS FAILURES
# ============================================================

test_messages = [

    "yaar 250 ka random expense ho gaya",

    "500 ka miscellaneous kharcha ho gaya",

    "kal kuch ajeeb sa kharcha hua"
]


print("=" * 70)
print("FINAL HYBRID PARSER TEST")
print("=" * 70)


for message in test_messages:

    result = parse_whatsapp_message_final(
        message
    )

    print("\nMessage:", message)

    print(
        "Amount:",
        result["amount"]
    )

    print(
        "Category:",
        result["category"]
    )

    print(
        "Type:",
        result["type"]
    )

    print(
        "Source:",
        result["category_source"]
    )

    print(
        "Confidence:",
        round(
            result["category_confidence"],
            4
        )
    )

======================================================================
FINAL HYBRID PARSER TEST
======================================================================

Message: yaar 250 ka random expense ho gaya
Amount: 250.0
Category: Other
Type: Expense
Source: rule
Confidence: 1.0

Message: 500 ka miscellaneous kharcha ho gaya
Amount: 500.0
Category: Other
Type: Expense
Source: rule
Confidence: 1.0

Message: kal kuch ajeeb sa kharcha hua
Amount: None
Category: Household
Type: Expense
Source: muril
Confidence: 0.8976

In [32]:
# ============================================================
# STEP 30 — PRODUCTION-SAFE WHATSAPP PARSER
# ============================================================

import json
import torch


# ============================================================
# 1. CONFIDENCE THRESHOLD
# ============================================================

MURIL_CONFIDENCE_THRESHOLD = 0.95


# ============================================================
# 2. SAFE FINAL PARSER
# ============================================================

def parse_whatsapp_message_production(text):

    # --------------------------------------------------------
    # Extract amount
    # --------------------------------------------------------

    amount = extract_amount(text)

    # --------------------------------------------------------
    # Detect transaction type
    # --------------------------------------------------------

    transaction_type = rule_based_type(text)

    # --------------------------------------------------------
    # First try deterministic rules
    # --------------------------------------------------------

    rule_category = rule_based_category(text)

    category_source = None
    category_confidence = None
    category = None

    # --------------------------------------------------------
    # RULE MATCH
    # --------------------------------------------------------

    if rule_category is not None:

        category = rule_category

        category_source = "rule"

        category_confidence = 1.0

    # --------------------------------------------------------
    # MÚRIL FALLBACK
    # --------------------------------------------------------

    else:

        muril_category, muril_confidence = (
            muril_category_prediction(text)
        )

        if (
            muril_confidence
            >=
            MURIL_CONFIDENCE_THRESHOLD
        ):

            category = muril_category

            category_source = "muril"

            category_confidence = (
                muril_confidence
            )

        else:

            category = None

            category_source = "review"

            category_confidence = (
                muril_confidence
            )

    # --------------------------------------------------------
    # DETERMINE WHETHER TRANSACTION IS SAFE TO SAVE
    # --------------------------------------------------------

    ready_to_save = (

        amount is not None

        and

        category is not None

        and

        transaction_type is not None
    )

    # --------------------------------------------------------
    # REVIEW REASON
    # --------------------------------------------------------

    review_reason = None

    if amount is None:

        review_reason = (
            "Amount could not be extracted"
        )

    elif category is None:

        review_reason = (
            "Category confidence is below threshold"
        )

    # --------------------------------------------------------
    # FINAL STRUCTURED RESULT
    # --------------------------------------------------------

    result = {

        "text": text,

        "amount": amount,

        "category": category,

        "type": transaction_type,

        "category_source": category_source,

        "category_confidence":
            round(
                category_confidence,
                4
            )
            if category_confidence is not None
            else None,

        "ready_to_save":
            ready_to_save,

        "review_reason":
            review_reason
    }

    return result


# ============================================================
# 3. TEST MESSAGES
# ============================================================

test_messages = [

    "yaar 250 ka pizza mangaya",

    "amazon se 1800 ke shoes liye",

    "doctor ko 600 diye",

    "uber se ghar aaya 220",

    "aaj salary 45000 aa gayi",

    "yaar 250 ka random expense ho gaya",

    "500 ka miscellaneous kharcha ho gaya",

    "kal kuch ajeeb sa kharcha hua"
]


# ============================================================
# 4. DISPLAY RESULTS
# ============================================================

print("=" * 70)
print("PRODUCTION-SAFE WHATSAPP PARSER")
print("=" * 70)

for message in test_messages:

    result = parse_whatsapp_message_production(
        message
    )

    print("\nMessage:")
    print(message)

    print("\nStructured result:")

    print(
        json.dumps(
            result,
            indent=2,
            ensure_ascii=False
        )
    )

======================================================================
PRODUCTION-SAFE WHATSAPP PARSER
======================================================================

Message:
yaar 250 ka pizza mangaya

Structured result:
{
  "text": "yaar 250 ka pizza mangaya",
  "amount": 250.0,
  "category": "Food",
  "type": "Expense",
  "category_source": "rule",
  "category_confidence": 1.0,
  "ready_to_save": true,
  "review_reason": null
}

Message:
amazon se 1800 ke shoes liye

Structured result:
{
  "text": "amazon se 1800 ke shoes liye",
  "amount": 1800.0,
  "category": "Apparel",
  "type": "Expense",
  "category_source": "rule",
  "category_confidence": 1.0,
  "ready_to_save": true,
  "review_reason": null
}

Message:
doctor ko 600 diye

Structured result:
{
  "text": "doctor ko 600 diye",
  "amount": 600.0,
  "category": "Health",
  "type": "Expense",
  "category_source": "rule",
  "category_confidence": 1.0,
  "ready_to_save": true,
  "review_reason": null
}

Message:
uber se ghar aaya 220

Structured result:
{
  "text": "uber se ghar aaya 220",
  "amount": 220.0,
  "category": "Transportation",
  "type": "Expense",
  "category_source": "rule",
  "category_confidence": 1.0,
  "ready_to_save": true,
  "review_reason": null
}

Message:
aaj salary 45000 aa gayi

Structured result:
{
  "text": "aaj salary 45000 aa gayi",
  "amount": 45000.0,
  "category": "Salary",
  "type": "Income",
  "category_source": "rule",
  "category_confidence": 1.0,
  "ready_to_save": true,
  "review_reason": null
}

Message:
yaar 250 ka random expense ho gaya

Structured result:
{
  "text": "yaar 250 ka random expense ho gaya",
  "amount": 250.0,
  "category": "Other",
  "type": "Expense",
  "category_source": "rule",
  "category_confidence": 1.0,
  "ready_to_save": true,
  "review_reason": null
}

Message:
500 ka miscellaneous kharcha ho gaya

Structured result:
{
  "text": "500 ka miscellaneous kharcha ho gaya",
  "amount": 500.0,
  "category": "Other",
  "type": "Expense",
  "category_source": "rule",
  "category_confidence": 1.0,
  "ready_to_save": true,
  "review_reason": null
}

Message:
kal kuch ajeeb sa kharcha hua

Structured result:
{
  "text": "kal kuch ajeeb sa kharcha hua",
  "amount": null,
  "category": null,
  "type": "Expense",
  "category_source": "review",
  "category_confidence": 0.8976,
  "ready_to_save": false,
  "review_reason": "Amount could not be extracted"
}

In [33]:
# ============================================================
# STEP 31 — DATABASE-READY TRANSACTION JSON
# ============================================================

import json


def create_database_payload(text):

    result = parse_whatsapp_message_production(text)

    # --------------------------------------------------------
    # CASE 1: SAFE TO SAVE
    # --------------------------------------------------------

    if result["ready_to_save"]:

        payload = {
            "amount": result["amount"],
            "category": result["category"],
            "type": result["type"],
            "description": result["text"]
        }

        return {
            "status": "success",
            "save_to_database": True,
            "transaction": payload
        }

    # --------------------------------------------------------
    # CASE 2: NEEDS REVIEW
    # --------------------------------------------------------

    return {
        "status": "needs_review",
        "save_to_database": False,
        "transaction": None,
        "message": (
            "I couldn't understand this transaction "
            "completely. Please provide the amount "
            "and a little more detail."
        )
    }


# ============================================================
# TEST
# ============================================================

messages = [

    "yaar 250 ka pizza mangaya",

    "amazon se 1800 ke shoes liye",

    "doctor ko 600 diye",

    "uber se ghar aaya 220",

    "aaj salary 45000 aa gayi",

    "500 ka miscellaneous kharcha ho gaya",

    "kal kuch ajeeb sa kharcha hua"
]


print("=" * 70)
print("DATABASE-READY WHATSAPP PAYLOADS")
print("=" * 70)

for message in messages:

    print("\nIncoming WhatsApp message:")
    print(message)

    payload = create_database_payload(
        message
    )

    print("\nBackend payload:")

    print(
        json.dumps(
            payload,
            indent=2,
            ensure_ascii=False
        )
    )

======================================================================
DATABASE-READY WHATSAPP PAYLOADS
======================================================================

Incoming WhatsApp message:
yaar 250 ka pizza mangaya

Backend payload:
{
  "status": "success",
  "save_to_database": true,
  "transaction": {
    "amount": 250.0,
    "category": "Food",
    "type": "Expense",
    "description": "yaar 250 ka pizza mangaya"
  }
}

Incoming WhatsApp message:
amazon se 1800 ke shoes liye

Backend payload:
{
  "status": "success",
  "save_to_database": true,
  "transaction": {
    "amount": 1800.0,
    "category": "Apparel",
    "type": "Expense",
    "description": "amazon se 1800 ke shoes liye"
  }
}

Incoming WhatsApp message:
doctor ko 600 diye

Backend payload:
{
  "status": "success",
  "save_to_database": true,
  "transaction": {
    "amount": 600.0,
    "category": "Health",
    "type": "Expense",
    "description": "doctor ko 600 diye"
  }
}

Incoming WhatsApp message:
uber se ghar aaya 220

Backend payload:
{
  "status": "success",
  "save_to_database": true,
  "transaction": {
    "amount": 220.0,
    "category": "Transportation",
    "type": "Expense",
    "description": "uber se ghar aaya 220"
  }
}

Incoming WhatsApp message:
aaj salary 45000 aa gayi

Backend payload:
{
  "status": "success",
  "save_to_database": true,
  "transaction": {
    "amount": 45000.0,
    "category": "Salary",
    "type": "Income",
    "description": "aaj salary 45000 aa gayi"
  }
}

Incoming WhatsApp message:
500 ka miscellaneous kharcha ho gaya

Backend payload:
{
  "status": "success",
  "save_to_database": true,
  "transaction": {
    "amount": 500.0,
    "category": "Other",
    "type": "Expense",
    "description": "500 ka miscellaneous kharcha ho gaya"
  }
}

Incoming WhatsApp message:
kal kuch ajeeb sa kharcha hua

Backend payload:
{
  "status": "needs_review",
  "save_to_database": false,
  "transaction": null,
  "message": "I couldn't understand this transaction completely. Please provide the amount and a little more detail."
}

In [34]:


# ============================================================
# STEP 32 — CREATE API VERSION OF THE PARSER
# ============================================================

from fastapi import FastAPI
from pydantic import BaseModel
import json


# ============================================================
# 1. CREATE FASTAPI APP
# ============================================================

app = FastAPI(
    title="WhatsApp Finance Parser",
    description="AI-powered WhatsApp transaction parser",
    version="1.0.0"
)


# ============================================================
# 2. REQUEST FORMAT
# ============================================================

class TransactionRequest(BaseModel):

    message: str


# ============================================================
# 3. HEALTH CHECK
# ============================================================

@app.get("/")
def root():

    return {
        "status": "ok",
        "service": "WhatsApp Finance Parser"
    }


# ============================================================
# 4. PARSE TRANSACTION ENDPOINT
# ============================================================

@app.post("/parse-transaction")
def parse_transaction(
    request: TransactionRequest
):

    result = create_database_payload(
        request.message
    )

    return result


# ============================================================
# 5. SHOW ROUTES
# ============================================================

print("=" * 70)
print("FASTAPI APPLICATION CREATED")
print("=" * 70)

print("Available endpoints:")

print("GET  /")
print("POST /parse-transaction")

======================================================================
FASTAPI APPLICATION CREATED
======================================================================
Available endpoints:
GET  /
POST /parse-transaction

In [35]:
# ============================================================
# STEP 33 — TEST FASTAPI ENDPOINT LOCALLY
# ============================================================

from fastapi.testclient import TestClient


# ============================================================
# 1. CREATE TEST CLIENT
# ============================================================

client = TestClient(app)


# ============================================================
# 2. TEST HEALTH CHECK
# ============================================================

print("=" * 70)
print("TEST 1 — HEALTH CHECK")
print("=" * 70)

response = client.get("/")

print("Status code:", response.status_code)

print("Response:")

print(
    response.json()
)


# ============================================================
# 3. TEST TRANSACTION PARSER
# ============================================================

print("\n" + "=" * 70)
print("TEST 2 — TRANSACTION PARSER")
print("=" * 70)

test_message = {
    "message": "yaar 250 ka pizza mangaya"
}

response = client.post(
    "/parse-transaction",
    json=test_message
)

print("Status code:", response.status_code)

print("Response:")

print(
    response.json()
)


# ============================================================
# 4. TEST ANOTHER MESSAGE
# ============================================================

print("\n" + "=" * 70)
print("TEST 3 — SALARY")
print("=" * 70)

test_message = {
    "message": "aaj salary 45000 aa gayi"
}

response = client.post(
    "/parse-transaction",
    json=test_message
)

print("Status code:", response.status_code)

print("Response:")

print(
    response.json()
)


# ============================================================
# 5. TEST REVIEW CASE
# ============================================================

print("\n" + "=" * 70)
print("TEST 4 — UNCLEAR MESSAGE")
print("=" * 70)

test_message = {
    "message": "kal kuch ajeeb sa kharcha hua"
}

response = client.post(
    "/parse-transaction",
    json=test_message
)

print("Status code:", response.status_code)

print("Response:")

print(
    response.json()
)

======================================================================
TEST 1 — HEALTH CHECK
======================================================================
Status code: 200
Response:
{'status': 'ok', 'service': 'WhatsApp Finance Parser'}

======================================================================
TEST 2 — TRANSACTION PARSER
======================================================================
Status code: 200
Response:
{'status': 'success', 'save_to_database': True, 'transaction': {'amount': 250.0, 'category': 'Food', 'type': 'Expense', 'description': 'yaar 250 ka pizza mangaya'}}

======================================================================
TEST 3 — SALARY
======================================================================
Status code: 200
Response:
{'status': 'success', 'save_to_database': True, 'transaction': {'amount': 45000.0, 'category': 'Salary', 'type': 'Income', 'description': 'aaj salary 45000 aa gayi'}}

======================================================================
TEST 4 — UNCLEAR MESSAGE
======================================================================
Status code: 200
Response:
{'status': 'needs_review', 'save_to_database': False, 'transaction': None, 'message': "I couldn't understand this transaction completely. Please provide the amount and a little more detail."}

In [36]:
# ============================================================
# STEP 34 — START FASTAPI SERVER
# ============================================================

import subprocess
import sys
import time

print("=" * 70)
print("CHECKING UVICORN")
print("=" * 70)

# Install uvicorn if necessary
subprocess.run(
    [
        sys.executable,
        "-m",
        "pip",
        "install",
        "uvicorn",
        "-q"
    ],
    check=True
)

print("Uvicorn is ready.")


# ============================================================
# START SERVER
# ============================================================

print("\n" + "=" * 70)
print("STARTING FASTAPI SERVER")
print("=" * 70)

server_process = subprocess.Popen(
    [
        sys.executable,
        "-m",
        "uvicorn",
        "__main__:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
    ],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

time.sleep(5)

print("Server process started.")
print("PID:", server_process.pid)
print("Local endpoint:")
print("http://127.0.0.1:8000")

======================================================================
CHECKING UVICORN
======================================================================
Uvicorn is ready.

======================================================================
STARTING FASTAPI SERVER
======================================================================
Server process started.
PID: 933
Local endpoint:
http://127.0.0.1:8000

In [37]:
# ============================================================
# TEST ACTUAL FASTAPI SERVER
# ============================================================

import requests

print("=" * 70)
print("TESTING LIVE SERVER")
print("=" * 70)


response = requests.get(
    "http://127.0.0.1:8000/"
)

print(
    "Health status:",
    response.status_code
)

print(
    "Health response:",
    response.json()
)


# ------------------------------------------------------------
# Test transaction endpoint
# ------------------------------------------------------------

response = requests.post(
    "http://127.0.0.1:8000/parse-transaction",
    json={
        "message": "yaar 250 ka pizza mangaya"
    }
)

print("\nTransaction status:", response.status_code)

print(
    "Transaction response:"
)

print(
    response.json()
)

======================================================================
TESTING LIVE SERVER
======================================================================

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7da5243a26c0>: Failed to establish a new connection: [Errno 111] Connection refused'))

In [38]:
# ============================================================
# STEP 34 — START FASTAPI INSIDE THE NOTEBOOK
# ============================================================

import threading
import time
import uvicorn


# ============================================================
# 1. CREATE UVICORN CONFIG
# ============================================================

config = uvicorn.Config(
    app,
    host="0.0.0.0",
    port=8000,
    log_level="info"
)


# ============================================================
# 2. CREATE SERVER
# ============================================================

server = uvicorn.Server(config)


# ============================================================
# 3. START SERVER IN BACKGROUND THREAD
# ============================================================

server_thread = threading.Thread(
    target=server.run,
    daemon=True
)

server_thread.start()


# ============================================================
# 4. WAIT FOR SERVER
# ============================================================

time.sleep(5)


print("=" * 70)
print("FASTAPI SERVER STATUS")
print("=" * 70)

print(
    "Server started:",
    server.started
)

print(
    "URL:",
    "http://127.0.0.1:8000"
)

INFO:     Started server process [58]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

======================================================================
FASTAPI SERVER STATUS
======================================================================
Server started: True
URL: http://127.0.0.1:8000

In [39]:
# ============================================================
# STEP 34B — TEST THE ACTUAL SERVER
# ============================================================

import requests


print("=" * 70)
print("TESTING LIVE FASTAPI SERVER")
print("=" * 70)


# ============================================================
# HEALTH CHECK
# ============================================================

response = requests.get(
    "http://127.0.0.1:8000/",
    timeout=10
)

print(
    "\nHealth status:",
    response.status_code
)

print(
    "Health response:",
    response.json()
)


# ============================================================
# TRANSACTION TEST
# ============================================================

response = requests.post(
    "http://127.0.0.1:8000/parse-transaction",
    json={
        "message": "yaar 250 ka pizza mangaya"
    },
    timeout=30
)

print(
    "\nTransaction status:",
    response.status_code
)

print(
    "Transaction response:"
)

print(
    response.json()
)

======================================================================
TESTING LIVE FASTAPI SERVER
======================================================================
INFO:     127.0.0.1:51250 - "GET / HTTP/1.1" 200 OK

Health status: 200
Health response: {'status': 'ok', 'service': 'WhatsApp Finance Parser'}
INFO:     127.0.0.1:51264 - "POST /parse-transaction HTTP/1.1" 200 OK

Transaction status: 200
Transaction response:
{'status': 'success', 'save_to_database': True, 'transaction': {'amount': 250.0, 'category': 'Food', 'type': 'Expense', 'description': 'yaar 250 ka pizza mangaya'}}

In [40]:
import os

for path in [
    "/kaggle/working/muril_original_best.pt",
    "/kaggle/working/muril_whatsapp_best.pt"
]:
    print(
        path,
        "->",
        os.path.exists(path)
    )

/kaggle/working/muril_original_best.pt -> True
/kaggle/working/muril_whatsapp_best.pt -> True

In [41]:
import os
import zipfile

files_to_backup = [
    "/kaggle/working/muril_whatsapp_best.pt",
    "/kaggle/working/muril_original_best.pt",
]

backup_path = "/kaggle/working/whatsapp_finance_ai_backup.zip"

with zipfile.ZipFile(
    backup_path,
    "w",
    zipfile.ZIP_DEFLATED
) as zipf:

    for file_path in files_to_backup:

        if os.path.exists(file_path):

            zipf.write(
                file_path,
                arcname=os.path.basename(file_path)
            )

print("Backup created:")
print(backup_path)
print("Size:", os.path.getsize(backup_path) / (1024 * 1024), "MB")

Backup created:
/kaggle/working/whatsapp_finance_ai_backup.zip
Size: 1682.9279518127441 MB

In [42]:
# ============================================================
# FINAL BACKUP CHECK
# ============================================================

import os

files = [
    "/kaggle/working/whatsapp_finance_ai_backup.zip",
    "/kaggle/working/muril_whatsapp_best.pt",
    "/kaggle/working/muril_original_best.pt"
]

print("=" * 70)
print("FINAL BACKUP CHECK")
print("=" * 70)

for file_path in files:

    exists = os.path.exists(file_path)

    print("\nFile:", os.path.basename(file_path))
    print("Exists:", exists)

    if exists:
        size_mb = os.path.getsize(file_path) / (1024 * 1024)
        print(f"Size: {size_mb:.2f} MB")

======================================================================
FINAL BACKUP CHECK
======================================================================

File: whatsapp_finance_ai_backup.zip
Exists: True
Size: 1682.93 MB

File: muril_whatsapp_best.pt
Exists: True
Size: 906.34 MB

File: muril_original_best.pt
Exists: True
Size: 906.34 MB

In [43]:
# ============================================================
# CREATE DOWNLOAD LINK
# ============================================================

from IPython.display import FileLink, display

backup_file = "/kaggle/working/whatsapp_finance_ai_backup.zip"

print("Your complete model backup:")
display(FileLink(backup_file))

Your complete model backup:

/kaggle/working/whatsapp_finance_ai_backup.zip